// Copyright (c) 2025 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: com/daml/ledger/api/v2/interactive/transaction/v1/interactive_submission_data_cb.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Fetch node
type Fetch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specific LF version of the node
	LfVersion   string `protobuf:"bytes,1,opt,name=lf_version,json=lfVersion,proto3" json:"lf_version,omitempty"`
	ContractId  string `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	PackageName string `protobuf:"bytes,3,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	// The identifier uses the package-id reference format.
	TemplateId    *Identifier `protobuf:"bytes,4,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Signatories   []string    `protobuf:"bytes,5,rep,name=signatories,proto3" json:"signatories,omitempty"`
	Stakeholders  []string    `protobuf:"bytes,6,rep,name=stakeholders,proto3" json:"stakeholders,omitempty"`
	ActingParties []string    `protobuf:"bytes,7,rep,name=acting_parties,json=actingParties,proto3" json:"acting_parties,omitempty"`
	// Optional
	InterfaceId   *Identifier `protobuf:"bytes,8,opt,name=interface_id,json=interfaceId,proto3" json:"interface_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fetch) Reset() {
	*x = Fetch{}
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fetch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fetch) ProtoMessage() {}

func (x *Fetch) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fetch.ProtoReflect.Descriptor instead.
func (*Fetch) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_rawDescGZIP(), []int{0}
}

func (x *Fetch) GetLfVersion() string {
	if x != nil {
		return x.LfVersion
	}
	return ""
}

func (x *Fetch) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *Fetch) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *Fetch) GetTemplateId() *Identifier {
	if x != nil {
		return x.TemplateId
	}
	return nil
}

func (x *Fetch) GetSignatories() []string {
	if x != nil {
		return x.Signatories
	}
	return nil
}

func (x *Fetch) GetStakeholders() []string {
	if x != nil {
		return x.Stakeholders
	}
	return nil
}

func (x *Fetch) GetActingParties() []string {
	if x != nil {
		return x.ActingParties
	}
	return nil
}

func (x *Fetch) GetInterfaceId() *Identifier {
	if x != nil {
		return x.InterfaceId
	}
	return nil
}

// Exercise node
type ExerciseDisplay struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specific LF version of the node
	LfVersion   string `protobuf:"bytes,1,opt,name=lf_version,json=lfVersion,proto3" json:"lf_version,omitempty"`
	ContractId  string `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	PackageName string `protobuf:"bytes,3,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	// The identifier uses the package-id reference format.
	TemplateId    *Identifier `protobuf:"bytes,4,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Signatories   []string    `protobuf:"bytes,5,rep,name=signatories,proto3" json:"signatories,omitempty"`
	Stakeholders  []string    `protobuf:"bytes,6,rep,name=stakeholders,proto3" json:"stakeholders,omitempty"`
	ActingParties []string    `protobuf:"bytes,7,rep,name=acting_parties,json=actingParties,proto3" json:"acting_parties,omitempty"`
	// The identifier uses the package-id reference format.
	InterfaceId     *Identifier `protobuf:"bytes,8,opt,name=interface_id,json=interfaceId,proto3" json:"interface_id,omitempty"`
	ChoiceId        string      `protobuf:"bytes,9,opt,name=choice_id,json=choiceId,proto3" json:"choice_id,omitempty"`
	ChosenValue     *Value      `protobuf:"bytes,10,opt,name=chosen_value,json=chosenValue,proto3" json:"chosen_value,omitempty"`
	Consuming       bool        `protobuf:"varint,11,opt,name=consuming,proto3" json:"consuming,omitempty"`
	Children        []string    `protobuf:"bytes,12,rep,name=children,proto3" json:"children,omitempty"`
	ExerciseResult  *Value      `protobuf:"bytes,13,opt,name=exercise_result,json=exerciseResult,proto3" json:"exercise_result,omitempty"`
	ChoiceObservers []string    `protobuf:"bytes,14,rep,name=choice_observers,json=choiceObservers,proto3" json:"choice_observers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExerciseDisplay) Reset() {
	*x = ExerciseDisplay{}
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseDisplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseDisplay) ProtoMessage() {}

func (x *ExerciseDisplay) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseDisplay.ProtoReflect.Descriptor instead.
func (*ExerciseDisplay) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_rawDescGZIP(), []int{1}
}

func (x *ExerciseDisplay) GetLfVersion() string {
	if x != nil {
		return x.LfVersion
	}
	return ""
}

func (x *ExerciseDisplay) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *ExerciseDisplay) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *ExerciseDisplay) GetTemplateId() *Identifier {
	if x != nil {
		return x.TemplateId
	}
	return nil
}

func (x *ExerciseDisplay) GetSignatories() []string {
	if x != nil {
		return x.Signatories
	}
	return nil
}

func (x *ExerciseDisplay) GetStakeholders() []string {
	if x != nil {
		return x.Stakeholders
	}
	return nil
}

func (x *ExerciseDisplay) GetActingParties() []string {
	if x != nil {
		return x.ActingParties
	}
	return nil
}

func (x *ExerciseDisplay) GetInterfaceId() *Identifier {
	if x != nil {
		return x.InterfaceId
	}
	return nil
}

func (x *ExerciseDisplay) GetChoiceId() string {
	if x != nil {
		return x.ChoiceId
	}
	return ""
}

func (x *ExerciseDisplay) GetChosenValue() *Value {
	if x != nil {
		return x.ChosenValue
	}
	return nil
}

func (x *ExerciseDisplay) GetConsuming() bool {
	if x != nil {
		return x.Consuming
	}
	return false
}

func (x *ExerciseDisplay) GetChildren() []string {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *ExerciseDisplay) GetExerciseResult() *Value {
	if x != nil {
		return x.ExerciseResult
	}
	return nil
}

func (x *ExerciseDisplay) GetChoiceObservers() []string {
	if x != nil {
		return x.ChoiceObservers
	}
	return nil
}

// Exercise node
type Exercise struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specific LF version of the node
	LfVersion   string `protobuf:"bytes,1,opt,name=lf_version,json=lfVersion,proto3" json:"lf_version,omitempty"`
	ContractId  string `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	PackageName string `protobuf:"bytes,3,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	// The identifier uses the package-id reference format.
	TemplateId    *Identifier `protobuf:"bytes,4,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Signatories   []string    `protobuf:"bytes,5,rep,name=signatories,proto3" json:"signatories,omitempty"`
	Stakeholders  []string    `protobuf:"bytes,6,rep,name=stakeholders,proto3" json:"stakeholders,omitempty"`
	ActingParties []string    `protobuf:"bytes,7,rep,name=acting_parties,json=actingParties,proto3" json:"acting_parties,omitempty"`
	// The identifier uses the package-id reference format.
	InterfaceId     *Identifier `protobuf:"bytes,8,opt,name=interface_id,json=interfaceId,proto3" json:"interface_id,omitempty"`
	ChoiceId        string      `protobuf:"bytes,9,opt,name=choice_id,json=choiceId,proto3" json:"choice_id,omitempty"`
	ChosenValue     *Value      `protobuf:"bytes,10,opt,name=chosen_value,json=chosenValue,proto3" json:"chosen_value,omitempty"`
	Consuming       bool        `protobuf:"varint,11,opt,name=consuming,proto3" json:"consuming,omitempty"`
	Children        []string    `protobuf:"bytes,12,rep,name=children,proto3" json:"children,omitempty"`
	ExerciseResult  *Value      `protobuf:"bytes,13,opt,name=exercise_result,json=exerciseResult,proto3" json:"exercise_result,omitempty"`
	ChoiceObservers []string    `protobuf:"bytes,14,rep,name=choice_observers,json=choiceObservers,proto3" json:"choice_observers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Exercise) Reset() {
	*x = Exercise{}
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exercise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exercise) ProtoMessage() {}

func (x *Exercise) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exercise.ProtoReflect.Descriptor instead.
func (*Exercise) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_rawDescGZIP(), []int{2}
}

func (x *Exercise) GetLfVersion() string {
	if x != nil {
		return x.LfVersion
	}
	return ""
}

func (x *Exercise) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *Exercise) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *Exercise) GetTemplateId() *Identifier {
	if x != nil {
		return x.TemplateId
	}
	return nil
}

func (x *Exercise) GetSignatories() []string {
	if x != nil {
		return x.Signatories
	}
	return nil
}

func (x *Exercise) GetStakeholders() []string {
	if x != nil {
		return x.Stakeholders
	}
	return nil
}

func (x *Exercise) GetActingParties() []string {
	if x != nil {
		return x.ActingParties
	}
	return nil
}

func (x *Exercise) GetInterfaceId() *Identifier {
	if x != nil {
		return x.InterfaceId
	}
	return nil
}

func (x *Exercise) GetChoiceId() string {
	if x != nil {
		return x.ChoiceId
	}
	return ""
}

func (x *Exercise) GetChosenValue() *Value {
	if x != nil {
		return x.ChosenValue
	}
	return nil
}

func (x *Exercise) GetConsuming() bool {
	if x != nil {
		return x.Consuming
	}
	return false
}

func (x *Exercise) GetChildren() []string {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *Exercise) GetExerciseResult() *Value {
	if x != nil {
		return x.ExerciseResult
	}
	return nil
}

func (x *Exercise) GetChoiceObservers() []string {
	if x != nil {
		return x.ChoiceObservers
	}
	return nil
}

// Another copy of Create node for display parsing.
type CreateDisplay struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specific LF version of the node
	LfVersion   string `protobuf:"bytes,1,opt,name=lf_version,json=lfVersion,proto3" json:"lf_version,omitempty"`
	ContractId  string `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	PackageName string `protobuf:"bytes,3,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	// The identifier uses the package-id reference format.
	TemplateId    *Identifier `protobuf:"bytes,4,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Argument      *Value      `protobuf:"bytes,5,opt,name=argument,proto3" json:"argument,omitempty"`
	Signatories   []string    `protobuf:"bytes,6,rep,name=signatories,proto3" json:"signatories,omitempty"`
	Stakeholders  []string    `protobuf:"bytes,7,rep,name=stakeholders,proto3" json:"stakeholders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDisplay) Reset() {
	*x = CreateDisplay{}
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDisplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDisplay) ProtoMessage() {}

func (x *CreateDisplay) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDisplay.ProtoReflect.Descriptor instead.
func (*CreateDisplay) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDisplay) GetLfVersion() string {
	if x != nil {
		return x.LfVersion
	}
	return ""
}

func (x *CreateDisplay) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *CreateDisplay) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *CreateDisplay) GetTemplateId() *Identifier {
	if x != nil {
		return x.TemplateId
	}
	return nil
}

func (x *CreateDisplay) GetArgument() *Value {
	if x != nil {
		return x.Argument
	}
	return nil
}

func (x *CreateDisplay) GetSignatories() []string {
	if x != nil {
		return x.Signatories
	}
	return nil
}

func (x *CreateDisplay) GetStakeholders() []string {
	if x != nil {
		return x.Stakeholders
	}
	return nil
}

// Create Node
type Create struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specific LF version of the node
	LfVersion   string `protobuf:"bytes,1,opt,name=lf_version,json=lfVersion,proto3" json:"lf_version,omitempty"`
	ContractId  string `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	PackageName string `protobuf:"bytes,3,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	// The identifier uses the package-id reference format.
	TemplateId    *Identifier `protobuf:"bytes,4,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Argument      *Value      `protobuf:"bytes,5,opt,name=argument,proto3" json:"argument,omitempty"`
	Signatories   []string    `protobuf:"bytes,6,rep,name=signatories,proto3" json:"signatories,omitempty"`
	Stakeholders  []string    `protobuf:"bytes,7,rep,name=stakeholders,proto3" json:"stakeholders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Create) Reset() {
	*x = Create{}
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Create) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create) ProtoMessage() {}

func (x *Create) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create.ProtoReflect.Descriptor instead.
func (*Create) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_rawDescGZIP(), []int{4}
}

func (x *Create) GetLfVersion() string {
	if x != nil {
		return x.LfVersion
	}
	return ""
}

func (x *Create) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *Create) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *Create) GetTemplateId() *Identifier {
	if x != nil {
		return x.TemplateId
	}
	return nil
}

func (x *Create) GetArgument() *Value {
	if x != nil {
		return x.Argument
	}
	return nil
}

func (x *Create) GetSignatories() []string {
	if x != nil {
		return x.Signatories
	}
	return nil
}

func (x *Create) GetStakeholders() []string {
	if x != nil {
		return x.Stakeholders
	}
	return nil
}

// Rollback Node
type Rollback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Children      []string               `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rollback) Reset() {
	*x = Rollback{}
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rollback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rollback) ProtoMessage() {}

func (x *Rollback) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rollback.ProtoReflect.Descriptor instead.
func (*Rollback) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_rawDescGZIP(), []int{5}
}

func (x *Rollback) GetChildren() []string {
	if x != nil {
		return x.Children
	}
	return nil
}

type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to NodeType:
	//
	//	*Node_Create
	//	*Node_Fetch
	//	*Node_Exercise
	//	*Node_Rollback
	NodeType      isNode_NodeType `protobuf_oneof:"node_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_rawDescGZIP(), []int{6}
}

func (x *Node) GetNodeType() isNode_NodeType {
	if x != nil {
		return x.NodeType
	}
	return nil
}

func (x *Node) GetCreate() *Create {
	if x != nil {
		if x, ok := x.NodeType.(*Node_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *Node) GetFetch() *Fetch {
	if x != nil {
		if x, ok := x.NodeType.(*Node_Fetch); ok {
			return x.Fetch
		}
	}
	return nil
}

func (x *Node) GetExercise() *Exercise {
	if x != nil {
		if x, ok := x.NodeType.(*Node_Exercise); ok {
			return x.Exercise
		}
	}
	return nil
}

func (x *Node) GetRollback() *Rollback {
	if x != nil {
		if x, ok := x.NodeType.(*Node_Rollback); ok {
			return x.Rollback
		}
	}
	return nil
}

type isNode_NodeType interface {
	isNode_NodeType()
}

type Node_Create struct {
	Create *Create `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type Node_Fetch struct {
	Fetch *Fetch `protobuf:"bytes,2,opt,name=fetch,proto3,oneof"`
}

type Node_Exercise struct {
	Exercise *Exercise `protobuf:"bytes,3,opt,name=exercise,proto3,oneof"`
}

type Node_Rollback struct {
	Rollback *Rollback `protobuf:"bytes,4,opt,name=rollback,proto3,oneof"`
}

func (*Node_Create) isNode_NodeType() {}

func (*Node_Fetch) isNode_NodeType() {}

func (*Node_Exercise) isNode_NodeType() {}

func (*Node_Rollback) isNode_NodeType() {}

type NodeDisplay struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to NodeType:
	//
	//	*NodeDisplay_Create
	//	*NodeDisplay_Fetch
	//	*NodeDisplay_Exercise
	//	*NodeDisplay_Rollback
	NodeType      isNodeDisplay_NodeType `protobuf_oneof:"node_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeDisplay) Reset() {
	*x = NodeDisplay{}
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDisplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDisplay) ProtoMessage() {}

func (x *NodeDisplay) ProtoReflect() protoreflect.Message {
	mi := &file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDisplay.ProtoReflect.Descriptor instead.
func (*NodeDisplay) Descriptor() ([]byte, []int) {
	return file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_rawDescGZIP(), []int{7}
}

func (x *NodeDisplay) GetNodeType() isNodeDisplay_NodeType {
	if x != nil {
		return x.NodeType
	}
	return nil
}

func (x *NodeDisplay) GetCreate() *CreateDisplay {
	if x != nil {
		if x, ok := x.NodeType.(*NodeDisplay_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *NodeDisplay) GetFetch() *Fetch {
	if x != nil {
		if x, ok := x.NodeType.(*NodeDisplay_Fetch); ok {
			return x.Fetch
		}
	}
	return nil
}

func (x *NodeDisplay) GetExercise() *ExerciseDisplay {
	if x != nil {
		if x, ok := x.NodeType.(*NodeDisplay_Exercise); ok {
			return x.Exercise
		}
	}
	return nil
}

func (x *NodeDisplay) GetRollback() *Rollback {
	if x != nil {
		if x, ok := x.NodeType.(*NodeDisplay_Rollback); ok {
			return x.Rollback
		}
	}
	return nil
}

type isNodeDisplay_NodeType interface {
	isNodeDisplay_NodeType()
}

type NodeDisplay_Create struct {
	Create *CreateDisplay `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type NodeDisplay_Fetch struct {
	Fetch *Fetch `protobuf:"bytes,2,opt,name=fetch,proto3,oneof"`
}

type NodeDisplay_Exercise struct {
	Exercise *ExerciseDisplay `protobuf:"bytes,3,opt,name=exercise,proto3,oneof"`
}

type NodeDisplay_Rollback struct {
	Rollback *Rollback `protobuf:"bytes,4,opt,name=rollback,proto3,oneof"`
}

func (*NodeDisplay_Create) isNodeDisplay_NodeType() {}

func (*NodeDisplay_Fetch) isNodeDisplay_NodeType() {}

func (*NodeDisplay_Exercise) isNodeDisplay_NodeType() {}

func (*NodeDisplay_Rollback) isNodeDisplay_NodeType() {}

var File_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto protoreflect.FileDescriptor

const file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_rawDesc = "" +
	"\n" +
	"Vcom/daml/ledger/api/v2/interactive/transaction/v1/interactive_submission_data_cb.proto\x124com.daml.ledger.api.v2.interactive.transaction.v1.cb\x1a%com/daml/ledger/api/v2/value_cb.proto\"\xe9\x02\n" +
	"\x05Fetch\x12\x1d\n" +
	"\n" +
	"lf_version\x18\x01 \x01(\tR\tlfVersion\x12\x1f\n" +
	"\vcontract_id\x18\x02 \x01(\tR\n" +
	"contractId\x12!\n" +
	"\fpackage_name\x18\x03 \x01(\tR\vpackageName\x12F\n" +
	"\vtemplate_id\x18\x04 \x01(\v2%.com.daml.ledger.api.v2.cb.IdentifierR\n" +
	"templateId\x12 \n" +
	"\vsignatories\x18\x05 \x03(\tR\vsignatories\x12\"\n" +
	"\fstakeholders\x18\x06 \x03(\tR\fstakeholders\x12%\n" +
	"\x0eacting_parties\x18\a \x03(\tR\ractingParties\x12H\n" +
	"\finterface_id\x18\b \x01(\v2%.com.daml.ledger.api.v2.cb.IdentifierR\vinterfaceId\"\x85\x05\n" +
	"\x0fExerciseDisplay\x12\x1d\n" +
	"\n" +
	"lf_version\x18\x01 \x01(\tR\tlfVersion\x12\x1f\n" +
	"\vcontract_id\x18\x02 \x01(\tR\n" +
	"contractId\x12!\n" +
	"\fpackage_name\x18\x03 \x01(\tR\vpackageName\x12F\n" +
	"\vtemplate_id\x18\x04 \x01(\v2%.com.daml.ledger.api.v2.cb.IdentifierR\n" +
	"templateId\x12 \n" +
	"\vsignatories\x18\x05 \x03(\tR\vsignatories\x12\"\n" +
	"\fstakeholders\x18\x06 \x03(\tR\fstakeholders\x12%\n" +
	"\x0eacting_parties\x18\a \x03(\tR\ractingParties\x12H\n" +
	"\finterface_id\x18\b \x01(\v2%.com.daml.ledger.api.v2.cb.IdentifierR\vinterfaceId\x12\x1b\n" +
	"\tchoice_id\x18\t \x01(\tR\bchoiceId\x12C\n" +
	"\fchosen_value\x18\n" +
	" \x01(\v2 .com.daml.ledger.api.v2.cb.ValueR\vchosenValue\x12\x1c\n" +
	"\tconsuming\x18\v \x01(\bR\tconsuming\x12\x1a\n" +
	"\bchildren\x18\f \x03(\tR\bchildren\x12I\n" +
	"\x0fexercise_result\x18\r \x01(\v2 .com.daml.ledger.api.v2.cb.ValueR\x0eexerciseResult\x12)\n" +
	"\x10choice_observers\x18\x0e \x03(\tR\x0fchoiceObservers\"\xfe\x04\n" +
	"\bExercise\x12\x1d\n" +
	"\n" +
	"lf_version\x18\x01 \x01(\tR\tlfVersion\x12\x1f\n" +
	"\vcontract_id\x18\x02 \x01(\tR\n" +
	"contractId\x12!\n" +
	"\fpackage_name\x18\x03 \x01(\tR\vpackageName\x12F\n" +
	"\vtemplate_id\x18\x04 \x01(\v2%.com.daml.ledger.api.v2.cb.IdentifierR\n" +
	"templateId\x12 \n" +
	"\vsignatories\x18\x05 \x03(\tR\vsignatories\x12\"\n" +
	"\fstakeholders\x18\x06 \x03(\tR\fstakeholders\x12%\n" +
	"\x0eacting_parties\x18\a \x03(\tR\ractingParties\x12H\n" +
	"\finterface_id\x18\b \x01(\v2%.com.daml.ledger.api.v2.cb.IdentifierR\vinterfaceId\x12\x1b\n" +
	"\tchoice_id\x18\t \x01(\tR\bchoiceId\x12C\n" +
	"\fchosen_value\x18\n" +
	" \x01(\v2 .com.daml.ledger.api.v2.cb.ValueR\vchosenValue\x12\x1c\n" +
	"\tconsuming\x18\v \x01(\bR\tconsuming\x12\x1a\n" +
	"\bchildren\x18\f \x03(\tR\bchildren\x12I\n" +
	"\x0fexercise_result\x18\r \x01(\v2 .com.daml.ledger.api.v2.cb.ValueR\x0eexerciseResult\x12)\n" +
	"\x10choice_observers\x18\x0e \x03(\tR\x0fchoiceObservers\"\xbe\x02\n" +
	"\rCreateDisplay\x12\x1d\n" +
	"\n" +
	"lf_version\x18\x01 \x01(\tR\tlfVersion\x12\x1f\n" +
	"\vcontract_id\x18\x02 \x01(\tR\n" +
	"contractId\x12!\n" +
	"\fpackage_name\x18\x03 \x01(\tR\vpackageName\x12F\n" +
	"\vtemplate_id\x18\x04 \x01(\v2%.com.daml.ledger.api.v2.cb.IdentifierR\n" +
	"templateId\x12<\n" +
	"\bargument\x18\x05 \x01(\v2 .com.daml.ledger.api.v2.cb.ValueR\bargument\x12 \n" +
	"\vsignatories\x18\x06 \x03(\tR\vsignatories\x12\"\n" +
	"\fstakeholders\x18\a \x03(\tR\fstakeholders\"\xb7\x02\n" +
	"\x06Create\x12\x1d\n" +
	"\n" +
	"lf_version\x18\x01 \x01(\tR\tlfVersion\x12\x1f\n" +
	"\vcontract_id\x18\x02 \x01(\tR\n" +
	"contractId\x12!\n" +
	"\fpackage_name\x18\x03 \x01(\tR\vpackageName\x12F\n" +
	"\vtemplate_id\x18\x04 \x01(\v2%.com.daml.ledger.api.v2.cb.IdentifierR\n" +
	"templateId\x12<\n" +
	"\bargument\x18\x05 \x01(\v2 .com.daml.ledger.api.v2.cb.ValueR\bargument\x12 \n" +
	"\vsignatories\x18\x06 \x03(\tR\vsignatories\x12\"\n" +
	"\fstakeholders\x18\a \x03(\tR\fstakeholders\"&\n" +
	"\bRollback\x12\x1a\n" +
	"\bchildren\x18\x01 \x03(\tR\bchildren\"\xfc\x02\n" +
	"\x04Node\x12V\n" +
	"\x06create\x18\x01 \x01(\v2<.com.daml.ledger.api.v2.interactive.transaction.v1.cb.CreateH\x00R\x06create\x12S\n" +
	"\x05fetch\x18\x02 \x01(\v2;.com.daml.ledger.api.v2.interactive.transaction.v1.cb.FetchH\x00R\x05fetch\x12\\\n" +
	"\bexercise\x18\x03 \x01(\v2>.com.daml.ledger.api.v2.interactive.transaction.v1.cb.ExerciseH\x00R\bexercise\x12\\\n" +
	"\brollback\x18\x04 \x01(\v2>.com.daml.ledger.api.v2.interactive.transaction.v1.cb.RollbackH\x00R\brollbackB\v\n" +
	"\tnode_type\"\x91\x03\n" +
	"\vNodeDisplay\x12]\n" +
	"\x06create\x18\x01 \x01(\v2C.com.daml.ledger.api.v2.interactive.transaction.v1.cb.CreateDisplayH\x00R\x06create\x12S\n" +
	"\x05fetch\x18\x02 \x01(\v2;.com.daml.ledger.api.v2.interactive.transaction.v1.cb.FetchH\x00R\x05fetch\x12c\n" +
	"\bexercise\x18\x03 \x01(\v2E.com.daml.ledger.api.v2.interactive.transaction.v1.cb.ExerciseDisplayH\x00R\bexercise\x12\\\n" +
	"\brollback\x18\x04 \x01(\v2>.com.daml.ledger.api.v2.interactive.transaction.v1.cb.RollbackH\x00R\brollbackB\v\n" +
	"\tnode_typeB\xd7\x01\n" +
	"4com.daml.ledger.api.v2.interactive.transaction.v1.cbB%InteractiveSubmissionDataOuterCbClassZAgithub.com/smartcontractkit/chainlink-canton/example/ledger/proto\xaa\x024Com.Daml.Ledger.Api.V2.Interactive.Transaction.V1.CBb\x06proto3"

var (
	file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_rawDescOnce sync.Once
	file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_rawDescData []byte
)

func file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_rawDescGZIP() []byte {
	file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_rawDescOnce.Do(func() {
		file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_rawDesc), len(file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_rawDesc)))
	})
	return file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_rawDescData
}

var file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_goTypes = []any{
	(*Fetch)(nil),           // 0: com.daml.ledger.api.v2.interactive.transaction.v1.cb.Fetch
	(*ExerciseDisplay)(nil), // 1: com.daml.ledger.api.v2.interactive.transaction.v1.cb.ExerciseDisplay
	(*Exercise)(nil),        // 2: com.daml.ledger.api.v2.interactive.transaction.v1.cb.Exercise
	(*CreateDisplay)(nil),   // 3: com.daml.ledger.api.v2.interactive.transaction.v1.cb.CreateDisplay
	(*Create)(nil),          // 4: com.daml.ledger.api.v2.interactive.transaction.v1.cb.Create
	(*Rollback)(nil),        // 5: com.daml.ledger.api.v2.interactive.transaction.v1.cb.Rollback
	(*Node)(nil),            // 6: com.daml.ledger.api.v2.interactive.transaction.v1.cb.Node
	(*NodeDisplay)(nil),     // 7: com.daml.ledger.api.v2.interactive.transaction.v1.cb.NodeDisplay
	(*Identifier)(nil),      // 8: com.daml.ledger.api.v2.cb.Identifier
	(*Value)(nil),           // 9: com.daml.ledger.api.v2.cb.Value
}
var file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_depIdxs = []int32{
	8,  // 0: com.daml.ledger.api.v2.interactive.transaction.v1.cb.Fetch.template_id:type_name -> com.daml.ledger.api.v2.cb.Identifier
	8,  // 1: com.daml.ledger.api.v2.interactive.transaction.v1.cb.Fetch.interface_id:type_name -> com.daml.ledger.api.v2.cb.Identifier
	8,  // 2: com.daml.ledger.api.v2.interactive.transaction.v1.cb.ExerciseDisplay.template_id:type_name -> com.daml.ledger.api.v2.cb.Identifier
	8,  // 3: com.daml.ledger.api.v2.interactive.transaction.v1.cb.ExerciseDisplay.interface_id:type_name -> com.daml.ledger.api.v2.cb.Identifier
	9,  // 4: com.daml.ledger.api.v2.interactive.transaction.v1.cb.ExerciseDisplay.chosen_value:type_name -> com.daml.ledger.api.v2.cb.Value
	9,  // 5: com.daml.ledger.api.v2.interactive.transaction.v1.cb.ExerciseDisplay.exercise_result:type_name -> com.daml.ledger.api.v2.cb.Value
	8,  // 6: com.daml.ledger.api.v2.interactive.transaction.v1.cb.Exercise.template_id:type_name -> com.daml.ledger.api.v2.cb.Identifier
	8,  // 7: com.daml.ledger.api.v2.interactive.transaction.v1.cb.Exercise.interface_id:type_name -> com.daml.ledger.api.v2.cb.Identifier
	9,  // 8: com.daml.ledger.api.v2.interactive.transaction.v1.cb.Exercise.chosen_value:type_name -> com.daml.ledger.api.v2.cb.Value
	9,  // 9: com.daml.ledger.api.v2.interactive.transaction.v1.cb.Exercise.exercise_result:type_name -> com.daml.ledger.api.v2.cb.Value
	8,  // 10: com.daml.ledger.api.v2.interactive.transaction.v1.cb.CreateDisplay.template_id:type_name -> com.daml.ledger.api.v2.cb.Identifier
	9,  // 11: com.daml.ledger.api.v2.interactive.transaction.v1.cb.CreateDisplay.argument:type_name -> com.daml.ledger.api.v2.cb.Value
	8,  // 12: com.daml.ledger.api.v2.interactive.transaction.v1.cb.Create.template_id:type_name -> com.daml.ledger.api.v2.cb.Identifier
	9,  // 13: com.daml.ledger.api.v2.interactive.transaction.v1.cb.Create.argument:type_name -> com.daml.ledger.api.v2.cb.Value
	4,  // 14: com.daml.ledger.api.v2.interactive.transaction.v1.cb.Node.create:type_name -> com.daml.ledger.api.v2.interactive.transaction.v1.cb.Create
	0,  // 15: com.daml.ledger.api.v2.interactive.transaction.v1.cb.Node.fetch:type_name -> com.daml.ledger.api.v2.interactive.transaction.v1.cb.Fetch
	2,  // 16: com.daml.ledger.api.v2.interactive.transaction.v1.cb.Node.exercise:type_name -> com.daml.ledger.api.v2.interactive.transaction.v1.cb.Exercise
	5,  // 17: com.daml.ledger.api.v2.interactive.transaction.v1.cb.Node.rollback:type_name -> com.daml.ledger.api.v2.interactive.transaction.v1.cb.Rollback
	3,  // 18: com.daml.ledger.api.v2.interactive.transaction.v1.cb.NodeDisplay.create:type_name -> com.daml.ledger.api.v2.interactive.transaction.v1.cb.CreateDisplay
	0,  // 19: com.daml.ledger.api.v2.interactive.transaction.v1.cb.NodeDisplay.fetch:type_name -> com.daml.ledger.api.v2.interactive.transaction.v1.cb.Fetch
	1,  // 20: com.daml.ledger.api.v2.interactive.transaction.v1.cb.NodeDisplay.exercise:type_name -> com.daml.ledger.api.v2.interactive.transaction.v1.cb.ExerciseDisplay
	5,  // 21: com.daml.ledger.api.v2.interactive.transaction.v1.cb.NodeDisplay.rollback:type_name -> com.daml.ledger.api.v2.interactive.transaction.v1.cb.Rollback
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() {
	file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_init()
}
func file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_init() {
	if File_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto != nil {
		return
	}
	file_com_daml_ledger_api_v2_value_cb_proto_init()
	file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_msgTypes[6].OneofWrappers = []any{
		(*Node_Create)(nil),
		(*Node_Fetch)(nil),
		(*Node_Exercise)(nil),
		(*Node_Rollback)(nil),
	}
	file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_msgTypes[7].OneofWrappers = []any{
		(*NodeDisplay_Create)(nil),
		(*NodeDisplay_Fetch)(nil),
		(*NodeDisplay_Exercise)(nil),
		(*NodeDisplay_Rollback)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_rawDesc), len(file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_goTypes,
		DependencyIndexes: file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_depIdxs,
		MessageInfos:      file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_msgTypes,
	}.Build()
	File_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto = out.File
	file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_goTypes = nil
	file_com_daml_ledger_api_v2_interactive_transaction_v1_interactive_submission_data_cb_proto_depIdxs = nil
}
