// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc/metadata"
)

// NewMockServerStreamingClient creates a new instance of MockServerStreamingClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerStreamingClient[Res any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerStreamingClient[Res] {
	mock := &MockServerStreamingClient[Res]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServerStreamingClient is an autogenerated mock type for the ServerStreamingClient type
type MockServerStreamingClient[Res any] struct {
	mock.Mock
}

type MockServerStreamingClient_Expecter[Res any] struct {
	mock *mock.Mock
}

func (_m *MockServerStreamingClient[Res]) EXPECT() *MockServerStreamingClient_Expecter[Res] {
	return &MockServerStreamingClient_Expecter[Res]{mock: &_m.Mock}
}

// CloseSend provides a mock function for the type MockServerStreamingClient
func (_mock *MockServerStreamingClient[Res]) CloseSend() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseSend")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerStreamingClient_CloseSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSend'
type MockServerStreamingClient_CloseSend_Call[Res any] struct {
	*mock.Call
}

// CloseSend is a helper method to define mock.On call
func (_e *MockServerStreamingClient_Expecter[Res]) CloseSend() *MockServerStreamingClient_CloseSend_Call[Res] {
	return &MockServerStreamingClient_CloseSend_Call[Res]{Call: _e.mock.On("CloseSend")}
}

func (_c *MockServerStreamingClient_CloseSend_Call[Res]) Run(run func()) *MockServerStreamingClient_CloseSend_Call[Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerStreamingClient_CloseSend_Call[Res]) Return(err error) *MockServerStreamingClient_CloseSend_Call[Res] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerStreamingClient_CloseSend_Call[Res]) RunAndReturn(run func() error) *MockServerStreamingClient_CloseSend_Call[Res] {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockServerStreamingClient
func (_mock *MockServerStreamingClient[Res]) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockServerStreamingClient_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockServerStreamingClient_Context_Call[Res any] struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockServerStreamingClient_Expecter[Res]) Context() *MockServerStreamingClient_Context_Call[Res] {
	return &MockServerStreamingClient_Context_Call[Res]{Call: _e.mock.On("Context")}
}

func (_c *MockServerStreamingClient_Context_Call[Res]) Run(run func()) *MockServerStreamingClient_Context_Call[Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerStreamingClient_Context_Call[Res]) Return(context1 context.Context) *MockServerStreamingClient_Context_Call[Res] {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockServerStreamingClient_Context_Call[Res]) RunAndReturn(run func() context.Context) *MockServerStreamingClient_Context_Call[Res] {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function for the type MockServerStreamingClient
func (_mock *MockServerStreamingClient[Res]) Header() (metadata.MD, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 metadata.MD
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (metadata.MD, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerStreamingClient_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type MockServerStreamingClient_Header_Call[Res any] struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *MockServerStreamingClient_Expecter[Res]) Header() *MockServerStreamingClient_Header_Call[Res] {
	return &MockServerStreamingClient_Header_Call[Res]{Call: _e.mock.On("Header")}
}

func (_c *MockServerStreamingClient_Header_Call[Res]) Run(run func()) *MockServerStreamingClient_Header_Call[Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerStreamingClient_Header_Call[Res]) Return(mD metadata.MD, err error) *MockServerStreamingClient_Header_Call[Res] {
	_c.Call.Return(mD, err)
	return _c
}

func (_c *MockServerStreamingClient_Header_Call[Res]) RunAndReturn(run func() (metadata.MD, error)) *MockServerStreamingClient_Header_Call[Res] {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function for the type MockServerStreamingClient
func (_mock *MockServerStreamingClient[Res]) Recv() (*Res, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recv")
	}

	var r0 *Res
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*Res, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *Res); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Res)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerStreamingClient_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type MockServerStreamingClient_Recv_Call[Res any] struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *MockServerStreamingClient_Expecter[Res]) Recv() *MockServerStreamingClient_Recv_Call[Res] {
	return &MockServerStreamingClient_Recv_Call[Res]{Call: _e.mock.On("Recv")}
}

func (_c *MockServerStreamingClient_Recv_Call[Res]) Run(run func()) *MockServerStreamingClient_Recv_Call[Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerStreamingClient_Recv_Call[Res]) Return(v *Res, err error) *MockServerStreamingClient_Recv_Call[Res] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockServerStreamingClient_Recv_Call[Res]) RunAndReturn(run func() (*Res, error)) *MockServerStreamingClient_Recv_Call[Res] {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function for the type MockServerStreamingClient
func (_mock *MockServerStreamingClient[Res]) RecvMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerStreamingClient_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockServerStreamingClient_RecvMsg_Call[Res any] struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m any
func (_e *MockServerStreamingClient_Expecter[Res]) RecvMsg(m interface{}) *MockServerStreamingClient_RecvMsg_Call[Res] {
	return &MockServerStreamingClient_RecvMsg_Call[Res]{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockServerStreamingClient_RecvMsg_Call[Res]) Run(run func(m any)) *MockServerStreamingClient_RecvMsg_Call[Res] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerStreamingClient_RecvMsg_Call[Res]) Return(err error) *MockServerStreamingClient_RecvMsg_Call[Res] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerStreamingClient_RecvMsg_Call[Res]) RunAndReturn(run func(m any) error) *MockServerStreamingClient_RecvMsg_Call[Res] {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function for the type MockServerStreamingClient
func (_mock *MockServerStreamingClient[Res]) SendMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerStreamingClient_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockServerStreamingClient_SendMsg_Call[Res any] struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m any
func (_e *MockServerStreamingClient_Expecter[Res]) SendMsg(m interface{}) *MockServerStreamingClient_SendMsg_Call[Res] {
	return &MockServerStreamingClient_SendMsg_Call[Res]{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockServerStreamingClient_SendMsg_Call[Res]) Run(run func(m any)) *MockServerStreamingClient_SendMsg_Call[Res] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerStreamingClient_SendMsg_Call[Res]) Return(err error) *MockServerStreamingClient_SendMsg_Call[Res] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerStreamingClient_SendMsg_Call[Res]) RunAndReturn(run func(m any) error) *MockServerStreamingClient_SendMsg_Call[Res] {
	_c.Call.Return(run)
	return _c
}

// Trailer provides a mock function for the type MockServerStreamingClient
func (_mock *MockServerStreamingClient[Res]) Trailer() metadata.MD {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Trailer")
	}

	var r0 metadata.MD
	if returnFunc, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}
	return r0
}

// MockServerStreamingClient_Trailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trailer'
type MockServerStreamingClient_Trailer_Call[Res any] struct {
	*mock.Call
}

// Trailer is a helper method to define mock.On call
func (_e *MockServerStreamingClient_Expecter[Res]) Trailer() *MockServerStreamingClient_Trailer_Call[Res] {
	return &MockServerStreamingClient_Trailer_Call[Res]{Call: _e.mock.On("Trailer")}
}

func (_c *MockServerStreamingClient_Trailer_Call[Res]) Run(run func()) *MockServerStreamingClient_Trailer_Call[Res] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerStreamingClient_Trailer_Call[Res]) Return(mD metadata.MD) *MockServerStreamingClient_Trailer_Call[Res] {
	_c.Call.Return(mD)
	return _c
}

func (_c *MockServerStreamingClient_Trailer_Call[Res]) RunAndReturn(run func() metadata.MD) *MockServerStreamingClient_Trailer_Call[Res] {
	_c.Call.Return(run)
	return _c
}
