// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	contracts "github.com/smartcontractkit/chainlink-canton/contracts"
	mock "github.com/stretchr/testify/mock"

	v2 "github.com/digital-asset/dazl-client/v8/go/api/com/daml/ledger/api/v2"
)

// MockContractStore is an autogenerated mock type for the ContractStore type
type MockContractStore struct {
	mock.Mock
}

type MockContractStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContractStore) EXPECT() *MockContractStore_Expecter {
	return &MockContractStore_Expecter{mock: &_m.Mock}
}

// GetContract provides a mock function with given fields: ctx, instanceAddress
func (_m *MockContractStore) GetContract(ctx context.Context, instanceAddress contracts.InstanceAddress) *v2.ActiveContract {
	ret := _m.Called(ctx, instanceAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetContract")
	}

	var r0 *v2.ActiveContract
	if rf, ok := ret.Get(0).(func(context.Context, contracts.InstanceAddress) *v2.ActiveContract); ok {
		r0 = rf(ctx, instanceAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.ActiveContract)
		}
	}

	return r0
}

// MockContractStore_GetContract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContract'
type MockContractStore_GetContract_Call struct {
	*mock.Call
}

// GetContract is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceAddress contracts.InstanceAddress
func (_e *MockContractStore_Expecter) GetContract(ctx interface{}, instanceAddress interface{}) *MockContractStore_GetContract_Call {
	return &MockContractStore_GetContract_Call{Call: _e.mock.On("GetContract", ctx, instanceAddress)}
}

func (_c *MockContractStore_GetContract_Call) Run(run func(ctx context.Context, instanceAddress contracts.InstanceAddress)) *MockContractStore_GetContract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(contracts.InstanceAddress))
	})
	return _c
}

func (_c *MockContractStore_GetContract_Call) Return(_a0 *v2.ActiveContract) *MockContractStore_GetContract_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContractStore_GetContract_Call) RunAndReturn(run func(context.Context, contracts.InstanceAddress) *v2.ActiveContract) *MockContractStore_GetContract_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockContractStore creates a new instance of MockContractStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContractStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContractStore {
	mock := &MockContractStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
