// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/digital-asset/dazl-client/v8/go/api/com/daml/ledger/api/v2"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockStateServiceClient creates a new instance of MockStateServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStateServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStateServiceClient {
	mock := &MockStateServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStateServiceClient is an autogenerated mock type for the StateServiceClient type
type MockStateServiceClient struct {
	mock.Mock
}

type MockStateServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStateServiceClient) EXPECT() *MockStateServiceClient_Expecter {
	return &MockStateServiceClient_Expecter{mock: &_m.Mock}
}

// GetActiveContracts provides a mock function for the type MockStateServiceClient
func (_mock *MockStateServiceClient) GetActiveContracts(ctx context.Context, in *v2.GetActiveContractsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v2.GetActiveContractsResponse], error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetActiveContracts")
	}

	var r0 grpc.ServerStreamingClient[v2.GetActiveContractsResponse]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v2.GetActiveContractsRequest, ...grpc.CallOption) (grpc.ServerStreamingClient[v2.GetActiveContractsResponse], error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v2.GetActiveContractsRequest, ...grpc.CallOption) grpc.ServerStreamingClient[v2.GetActiveContractsResponse]); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.ServerStreamingClient[v2.GetActiveContractsResponse])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v2.GetActiveContractsRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStateServiceClient_GetActiveContracts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveContracts'
type MockStateServiceClient_GetActiveContracts_Call struct {
	*mock.Call
}

// GetActiveContracts is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v2.GetActiveContractsRequest
//   - opts ...grpc.CallOption
func (_e *MockStateServiceClient_Expecter) GetActiveContracts(ctx interface{}, in interface{}, opts ...interface{}) *MockStateServiceClient_GetActiveContracts_Call {
	return &MockStateServiceClient_GetActiveContracts_Call{Call: _e.mock.On("GetActiveContracts",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockStateServiceClient_GetActiveContracts_Call) Run(run func(ctx context.Context, in *v2.GetActiveContractsRequest, opts ...grpc.CallOption)) *MockStateServiceClient_GetActiveContracts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v2.GetActiveContractsRequest
		if args[1] != nil {
			arg1 = args[1].(*v2.GetActiveContractsRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockStateServiceClient_GetActiveContracts_Call) Return(serverStreamingClient grpc.ServerStreamingClient[v2.GetActiveContractsResponse], err error) *MockStateServiceClient_GetActiveContracts_Call {
	_c.Call.Return(serverStreamingClient, err)
	return _c
}

func (_c *MockStateServiceClient_GetActiveContracts_Call) RunAndReturn(run func(ctx context.Context, in *v2.GetActiveContractsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v2.GetActiveContractsResponse], error)) *MockStateServiceClient_GetActiveContracts_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectedSynchronizers provides a mock function for the type MockStateServiceClient
func (_mock *MockStateServiceClient) GetConnectedSynchronizers(ctx context.Context, in *v2.GetConnectedSynchronizersRequest, opts ...grpc.CallOption) (*v2.GetConnectedSynchronizersResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetConnectedSynchronizers")
	}

	var r0 *v2.GetConnectedSynchronizersResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v2.GetConnectedSynchronizersRequest, ...grpc.CallOption) (*v2.GetConnectedSynchronizersResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v2.GetConnectedSynchronizersRequest, ...grpc.CallOption) *v2.GetConnectedSynchronizersResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.GetConnectedSynchronizersResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v2.GetConnectedSynchronizersRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStateServiceClient_GetConnectedSynchronizers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectedSynchronizers'
type MockStateServiceClient_GetConnectedSynchronizers_Call struct {
	*mock.Call
}

// GetConnectedSynchronizers is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v2.GetConnectedSynchronizersRequest
//   - opts ...grpc.CallOption
func (_e *MockStateServiceClient_Expecter) GetConnectedSynchronizers(ctx interface{}, in interface{}, opts ...interface{}) *MockStateServiceClient_GetConnectedSynchronizers_Call {
	return &MockStateServiceClient_GetConnectedSynchronizers_Call{Call: _e.mock.On("GetConnectedSynchronizers",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockStateServiceClient_GetConnectedSynchronizers_Call) Run(run func(ctx context.Context, in *v2.GetConnectedSynchronizersRequest, opts ...grpc.CallOption)) *MockStateServiceClient_GetConnectedSynchronizers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v2.GetConnectedSynchronizersRequest
		if args[1] != nil {
			arg1 = args[1].(*v2.GetConnectedSynchronizersRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockStateServiceClient_GetConnectedSynchronizers_Call) Return(getConnectedSynchronizersResponse *v2.GetConnectedSynchronizersResponse, err error) *MockStateServiceClient_GetConnectedSynchronizers_Call {
	_c.Call.Return(getConnectedSynchronizersResponse, err)
	return _c
}

func (_c *MockStateServiceClient_GetConnectedSynchronizers_Call) RunAndReturn(run func(ctx context.Context, in *v2.GetConnectedSynchronizersRequest, opts ...grpc.CallOption) (*v2.GetConnectedSynchronizersResponse, error)) *MockStateServiceClient_GetConnectedSynchronizers_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestPrunedOffsets provides a mock function for the type MockStateServiceClient
func (_mock *MockStateServiceClient) GetLatestPrunedOffsets(ctx context.Context, in *v2.GetLatestPrunedOffsetsRequest, opts ...grpc.CallOption) (*v2.GetLatestPrunedOffsetsResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetLatestPrunedOffsets")
	}

	var r0 *v2.GetLatestPrunedOffsetsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v2.GetLatestPrunedOffsetsRequest, ...grpc.CallOption) (*v2.GetLatestPrunedOffsetsResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v2.GetLatestPrunedOffsetsRequest, ...grpc.CallOption) *v2.GetLatestPrunedOffsetsResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.GetLatestPrunedOffsetsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v2.GetLatestPrunedOffsetsRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStateServiceClient_GetLatestPrunedOffsets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestPrunedOffsets'
type MockStateServiceClient_GetLatestPrunedOffsets_Call struct {
	*mock.Call
}

// GetLatestPrunedOffsets is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v2.GetLatestPrunedOffsetsRequest
//   - opts ...grpc.CallOption
func (_e *MockStateServiceClient_Expecter) GetLatestPrunedOffsets(ctx interface{}, in interface{}, opts ...interface{}) *MockStateServiceClient_GetLatestPrunedOffsets_Call {
	return &MockStateServiceClient_GetLatestPrunedOffsets_Call{Call: _e.mock.On("GetLatestPrunedOffsets",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockStateServiceClient_GetLatestPrunedOffsets_Call) Run(run func(ctx context.Context, in *v2.GetLatestPrunedOffsetsRequest, opts ...grpc.CallOption)) *MockStateServiceClient_GetLatestPrunedOffsets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v2.GetLatestPrunedOffsetsRequest
		if args[1] != nil {
			arg1 = args[1].(*v2.GetLatestPrunedOffsetsRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockStateServiceClient_GetLatestPrunedOffsets_Call) Return(getLatestPrunedOffsetsResponse *v2.GetLatestPrunedOffsetsResponse, err error) *MockStateServiceClient_GetLatestPrunedOffsets_Call {
	_c.Call.Return(getLatestPrunedOffsetsResponse, err)
	return _c
}

func (_c *MockStateServiceClient_GetLatestPrunedOffsets_Call) RunAndReturn(run func(ctx context.Context, in *v2.GetLatestPrunedOffsetsRequest, opts ...grpc.CallOption) (*v2.GetLatestPrunedOffsetsResponse, error)) *MockStateServiceClient_GetLatestPrunedOffsets_Call {
	_c.Call.Return(run)
	return _c
}

// GetLedgerEnd provides a mock function for the type MockStateServiceClient
func (_mock *MockStateServiceClient) GetLedgerEnd(ctx context.Context, in *v2.GetLedgerEndRequest, opts ...grpc.CallOption) (*v2.GetLedgerEndResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetLedgerEnd")
	}

	var r0 *v2.GetLedgerEndResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v2.GetLedgerEndRequest, ...grpc.CallOption) (*v2.GetLedgerEndResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v2.GetLedgerEndRequest, ...grpc.CallOption) *v2.GetLedgerEndResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.GetLedgerEndResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v2.GetLedgerEndRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStateServiceClient_GetLedgerEnd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLedgerEnd'
type MockStateServiceClient_GetLedgerEnd_Call struct {
	*mock.Call
}

// GetLedgerEnd is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v2.GetLedgerEndRequest
//   - opts ...grpc.CallOption
func (_e *MockStateServiceClient_Expecter) GetLedgerEnd(ctx interface{}, in interface{}, opts ...interface{}) *MockStateServiceClient_GetLedgerEnd_Call {
	return &MockStateServiceClient_GetLedgerEnd_Call{Call: _e.mock.On("GetLedgerEnd",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockStateServiceClient_GetLedgerEnd_Call) Run(run func(ctx context.Context, in *v2.GetLedgerEndRequest, opts ...grpc.CallOption)) *MockStateServiceClient_GetLedgerEnd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v2.GetLedgerEndRequest
		if args[1] != nil {
			arg1 = args[1].(*v2.GetLedgerEndRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockStateServiceClient_GetLedgerEnd_Call) Return(getLedgerEndResponse *v2.GetLedgerEndResponse, err error) *MockStateServiceClient_GetLedgerEnd_Call {
	_c.Call.Return(getLedgerEndResponse, err)
	return _c
}

func (_c *MockStateServiceClient_GetLedgerEnd_Call) RunAndReturn(run func(ctx context.Context, in *v2.GetLedgerEndRequest, opts ...grpc.CallOption) (*v2.GetLedgerEndResponse, error)) *MockStateServiceClient_GetLedgerEnd_Call {
	_c.Call.Return(run)
	return _c
}
