// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	splice_api_token_holding_v1 "github.com/smartcontractkit/chainlink-canton/bindings/generated/splice/splice_api_token_holding_v1"
	mock "github.com/stretchr/testify/mock"

	v2 "github.com/digital-asset/dazl-client/v8/go/api/com/daml/ledger/api/v2"
)

// MockInstrumentHoldingStore is an autogenerated mock type for the InstrumentHoldingStore type
type MockInstrumentHoldingStore struct {
	mock.Mock
}

type MockInstrumentHoldingStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstrumentHoldingStore) EXPECT() *MockInstrumentHoldingStore_Expecter {
	return &MockInstrumentHoldingStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: key
func (_m *MockInstrumentHoldingStore) Get(key splice_api_token_holding_v1.InstrumentId) (*v2.DisclosedContract, bool) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v2.DisclosedContract
	var r1 bool
	if rf, ok := ret.Get(0).(func(splice_api_token_holding_v1.InstrumentId) (*v2.DisclosedContract, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(splice_api_token_holding_v1.InstrumentId) *v2.DisclosedContract); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.DisclosedContract)
		}
	}

	if rf, ok := ret.Get(1).(func(splice_api_token_holding_v1.InstrumentId) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockInstrumentHoldingStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockInstrumentHoldingStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key splice_api_token_holding_v1.InstrumentId
func (_e *MockInstrumentHoldingStore_Expecter) Get(key interface{}) *MockInstrumentHoldingStore_Get_Call {
	return &MockInstrumentHoldingStore_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockInstrumentHoldingStore_Get_Call) Run(run func(key splice_api_token_holding_v1.InstrumentId)) *MockInstrumentHoldingStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(splice_api_token_holding_v1.InstrumentId))
	})
	return _c
}

func (_c *MockInstrumentHoldingStore_Get_Call) Return(value *v2.DisclosedContract, ok bool) *MockInstrumentHoldingStore_Get_Call {
	_c.Call.Return(value, ok)
	return _c
}

func (_c *MockInstrumentHoldingStore_Get_Call) RunAndReturn(run func(splice_api_token_holding_v1.InstrumentId) (*v2.DisclosedContract, bool)) *MockInstrumentHoldingStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInstrumentHoldingStore creates a new instance of MockInstrumentHoldingStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstrumentHoldingStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstrumentHoldingStore {
	mock := &MockInstrumentHoldingStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
