// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	contracts "github.com/smartcontractkit/chainlink-canton/contracts"
	mock "github.com/stretchr/testify/mock"

	v2 "github.com/digital-asset/dazl-client/v8/go/api/com/daml/ledger/api/v2"
)

// MockActiveContractStore is an autogenerated mock type for the ActiveContractStore type
type MockActiveContractStore struct {
	mock.Mock
}

type MockActiveContractStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActiveContractStore) EXPECT() *MockActiveContractStore_Expecter {
	return &MockActiveContractStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: key
func (_m *MockActiveContractStore) Get(key contracts.InstanceAddress) (*v2.ActiveContract, bool) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v2.ActiveContract
	var r1 bool
	if rf, ok := ret.Get(0).(func(contracts.InstanceAddress) (*v2.ActiveContract, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(contracts.InstanceAddress) *v2.ActiveContract); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.ActiveContract)
		}
	}

	if rf, ok := ret.Get(1).(func(contracts.InstanceAddress) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockActiveContractStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockActiveContractStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key contracts.InstanceAddress
func (_e *MockActiveContractStore_Expecter) Get(key interface{}) *MockActiveContractStore_Get_Call {
	return &MockActiveContractStore_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockActiveContractStore_Get_Call) Run(run func(key contracts.InstanceAddress)) *MockActiveContractStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(contracts.InstanceAddress))
	})
	return _c
}

func (_c *MockActiveContractStore_Get_Call) Return(value *v2.ActiveContract, ok bool) *MockActiveContractStore_Get_Call {
	_c.Call.Return(value, ok)
	return _c
}

func (_c *MockActiveContractStore_Get_Call) RunAndReturn(run func(contracts.InstanceAddress) (*v2.ActiveContract, bool)) *MockActiveContractStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockActiveContractStore creates a new instance of MockActiveContractStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActiveContractStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActiveContractStore {
	mock := &MockActiveContractStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
