[node.auth]
jwt = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyLXBhcnRpY2lwYW50MSIsImF1ZCI6WyJodHRwczovL2NoYWluLmxpbmsiXSwiZXhwIjoyMDg4NDQyMzQzLCJuYmYiOjE3NzMwODIzNDMsImlhdCI6MTc3MzA4MjM0M30.IPFC1soD4Mc1M-NdOm-F6J5nbEd4JnBNgpdzqxptRH8'
