environments:

  localnet:
    party: "ccip-owner::1220deadbeef0123456789abcdef0123456789abcdef0123456789abcdef0123456789"
    description: "Local development"
    contracts:
      router: "localnet-router"
      onRamp: "localnet-onramp"
      offRamp: "localnet-offramp"
      globalConfig: "localnet-globalconfig"
      feeQuoter: "localnet-feequoter"
      ccv: "localnet-ccv"
      tokenAdminRegistry: "localnet-tar"
      tokenPool: "localnet-tokenpool"
