environments:

  localnet:
    party: "ccip-owner::1220deadbeef0123456789abcdef0123456789abcdef0123456789abcdef0123456789"
    description: "Local development"
    contracts:
      router: "localnet"
      onRamp: "localnet"
      feeQuoter: "localnet"
      offRamp: "localnet"
      ccv: "localnet"
      tokenAdminRegistry: "localnet"
      tokenPool: "localnet"
