with-expecter: true

dir: ./internal/mocks
outpkg: mocks

packages:
  github.com/digital-asset/dazl-client/v8/go/api/com/daml/ledger/api/v2:
    interfaces:
      StateServiceClient:
      UpdateServiceClient:
  github.com/smartcontractkit/chainlink-canton/eds/internal/store:
    interfaces:
      ActiveContractStore:
      InstrumentHoldingStore:
  google.golang.org/grpc:
    interfaces:
      ServerStreamingClient:
