.PHONY: generate-daml-codecs
generate-daml-codecs:
	go run ./contracts/cmd/damlcodecs

.PHONY: compile-contracts
compile-contracts: generate-daml-codecs
	@echo "Compiling contracts..."
	dpm clean --all --multi-package-path ./contracts/
	go run ./contracts/cmd/compile -root ./contracts -artifacts ./contracts/dars

.PHONY: generate-bindings
generate-bindings:
	go run ./contracts/cmd/bindings

.PHONY: clean-codecs
clean-codecs: ## Remove auto-generated *CodecGen.daml files (regenerated by generate-daml-codecs).
	@find contracts -path '*/daml/CCIP/*CodecGen.daml' -not -path '*/.daml/*' -delete 2>/dev/null || true

.PHONY: contracts
contracts: clean-codecs compile-contracts generate-bindings

.PHONY: update-contract-version
update-contract-version: ## Update contract version and rebuild. Usage: make update-contract-version OLD=0.0.1 NEW=1.0.0
	@./contracts/scripts/update-version.sh $(OLD) $(NEW)
	@$(MAKE) contracts

.PHONY: go-generate
go-generate:
	go generate ./...

.PHONY: gomodtidy
gomodtidy: ## Run go mod tidy on all modules.
	go run github.com/jmank88/gomods@v0.1.7 tidy

.PHONY: test-daml-contracts
test-daml-contracts:
	go run ./contracts/cmd/test --root ./contracts

# Baseline-clean packages enforced in CI. Expand this list as lint debt is
# removed from the remaining Daml packages.
DAML_LINT_PACKAGES ?= \
	contracts/ccip/ccipreceiver \
	contracts/ccip/ccvs \
	contracts/ccip/client \
	contracts/ccip/feequoter \
	contracts/ccip/offramp \
	contracts/ccip/pools/burnMintTokenPool \
	contracts/ccip/pools/interfaces \
	contracts/ccip/pools/lockReleaseTokenPool \
	contracts/coin \
	contracts/mcms/test/globalconfig-v1 \
	contracts/test/interfaces \
	contracts/test/proxy \
	contracts/test/receiver \
	contracts/test/test

.PHONY: lint-daml-contracts
lint-daml-contracts: compile-contracts
	@echo "Linting Daml contracts..."
	@set -e; \
	for pkg_dir in $(DAML_LINT_PACKAGES); do \
		echo "dpm damlc lint $$pkg_dir"; \
		( cd "$$pkg_dir" && dpm damlc lint ); \
	done

.PHONY: lint-daml-contracts-all
lint-daml-contracts-all:
	@echo "Linting all Daml contracts..."
	@set -e; \
	find contracts -name daml.yaml -not -path '*/.daml/*' -print | sort | while read -r daml_yaml; do \
		pkg_dir=$$(dirname "$$daml_yaml"); \
		echo "dpm damlc lint $$pkg_dir"; \
		( cd "$$pkg_dir" && dpm damlc lint ); \
	done

# GolangCI-Lint targets

.PHONY: golangci-lint-main golangci-lint-integration-tests golangci-lint-party-ceremony golangci-lint-party-ceremony-integration-tests
golangci-lint-main: ## Run golangci-lint on the main module.
	golangci-lint run
golangci-lint-integration-tests: ## Run golangci-lint on the integration-tests module.
	cd integration-tests && golangci-lint run
golangci-lint-party-ceremony: ## Run golangci-lint on the party-ceremony module.
	cd party-ceremony && golangci-lint run
golangci-lint-party-ceremony-integration-tests: ## Run golangci-lint on the party-ceremony/integration-tests module.
	cd party-ceremony/integration-tests && golangci-lint run

.PHONY: golangci-lint-all
golangci-lint-all: golangci-lint-main golangci-lint-integration-tests golangci-lint-party-ceremony golangci-lint-party-ceremony-integration-tests ## Run golangci-lint on all modules.

.PHONY: golangci-lint-fix-main golangci-lint-fix-integration-tests golangci-lint-fix-party-ceremony golangci-lint-fix-party-ceremony-integration-tests
golangci-lint-fix-main: ## Run golangci-lint --fix on the main module.
	golangci-lint run --fix
golangci-lint-fix-integration-tests: ## Run golangci-lint --fix on the integration-tests module.
	cd integration-tests && golangci-lint run --fix
golangci-lint-fix-party-ceremony: ## Run golangci-lint --fix on the party-ceremony module.
	cd party-ceremony && golangci-lint run --fix
golangci-lint-fix-party-ceremony-integration-tests: ## Run golangci-lint --fix on the party-ceremony/integration-tests module.
	cd party-ceremony/integration-tests && golangci-lint run --fix

.PHONY: golangci-lint-fix-all
golangci-lint-fix-all: golangci-lint-fix-main golangci-lint-fix-integration-tests golangci-lint-fix-party-ceremony golangci-lint-fix-party-ceremony-integration-tests ## Run golangci-lint --fix on all modules.

## Run all fix targets.
## Compiles contracts, generates bindings, runs all go generates, runs go mod tidy, and runs golangci-lint --fix on all modules.
.PHONY: fix-all
fix-all: contracts go-generate gomodtidy golangci-lint-fix-all

.PHONY: build-committeeverifier
build-committeeverifier:
	docker build -t committeeverifier-canton:latest -f ccip/committee_verifier.Dockerfile .

.PHONY: build-eds
build-eds:
	docker build -t canton-eds:latest -f eds/eds.Dockerfile .

## Assuming chainlink-ccv is checked out in ../chainlink-ccv.
.PHONY: build-ccv-images
build-ccv-images:
	cd ../chainlink-ccv/build/devenv && just build-docker-dev

.PHONY: start-devenv
start-devenv: build-ccv-images build-committeeverifier build-eds
	cd ccip/devenv && go run cmd/ccv/main.go down && go run cmd/ccv/main.go up env-canton-evm.toml

.PHONY: run-e2e-tests
run-e2e-tests:
	cd ccip/devenv/tests/e2e && go test -timeout 5m -v -count 1 -run TestEVM2Canton_Basic && go test -timeout 5m -v -count 1 -run TestCanton2EVM_Basic

.PHONY: build-run-e2e-tests
build-run-e2e-tests: start-devenv run-e2e-tests

.PHONY: mocks
mocks:
	go run github.com/vektra/mockery/v3@v3.7.0
