canton.features.enable-testing-commands = yes

canton.remote-participants.sv {
  ledger-api {
    address = canton
    port = ${CANTON_PARTICIPANT_LEDGER_API_PORT_PREFIX}00
  }
  admin-api {
    address = canton
    port = ${CANTON_PARTICIPANT_ADMIN_API_PORT_PREFIX}00
  }
  token = ${SV_USER_TOKEN}
}

canton.remote-participants.participant1 {
  ledger-api {
    address = canton
    port = ${CANTON_PARTICIPANT_LEDGER_API_PORT_PREFIX}01
  }
  admin-api {
    address = canton
    port = ${CANTON_PARTICIPANT_ADMIN_API_PORT_PREFIX}01
  }
  token = ${PARTICIPANT1_USER_TOKEN}
}


canton.remote-participants.participant2 {
  ledger-api {
    address = canton
    port = ${CANTON_PARTICIPANT_LEDGER_API_PORT_PREFIX}02
  }
  admin-api {
    address = canton
    port = ${CANTON_PARTICIPANT_ADMIN_API_PORT_PREFIX}02
  }
  token = ${PARTICIPANT2_USER_TOKEN}
}


canton.remote-participants.participant3 {
  ledger-api {
    address = canton
    port = ${CANTON_PARTICIPANT_LEDGER_API_PORT_PREFIX}03
  }
  admin-api {
    address = canton
    port = ${CANTON_PARTICIPANT_ADMIN_API_PORT_PREFIX}03
  }
  token = ${PARTICIPANT3_USER_TOKEN}
}


canton.remote-participants.participant4 {
  ledger-api {
    address = canton
    port = ${CANTON_PARTICIPANT_LEDGER_API_PORT_PREFIX}04
  }
  admin-api {
    address = canton
    port = ${CANTON_PARTICIPANT_ADMIN_API_PORT_PREFIX}04
  }
  token = ${PARTICIPANT4_USER_TOKEN}
}


canton.remote-participants.participant5 {
  ledger-api {
    address = canton
    port = ${CANTON_PARTICIPANT_LEDGER_API_PORT_PREFIX}05
  }
  admin-api {
    address = canton
    port = ${CANTON_PARTICIPANT_ADMIN_API_PORT_PREFIX}05
  }
  token = ${PARTICIPANT5_USER_TOKEN}
}
