// Package tokenMetadataV1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package tokenMetadataV1

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// GetRegistryInfoResponse defines model for GetRegistryInfoResponse.
type GetRegistryInfoResponse struct {
	// AdminId The Daml party representing the registry app
	AdminId string `json:"adminId"`

	// SupportedApis Map from token standard API name to the minor version of the API supported, e.g.,
	// splice-api-token-metadata-v1 -> 1 where the `1` corresponds to the minor version.
	SupportedApis SupportedApis `json:"supportedApis"`
}

// Instrument defines model for Instrument.
type Instrument struct {
	// Decimals The number of decimal places used by the instrument.
	//
	// Must be a number between 0 and 10, as the Daml interfaces represent holding amounts as
	// `Decimal` values, which use 10 decimal places and are precise for 38 digits.
	// Setting this to 0 means that the instrument can only be held in whole units.
	//
	// This number SHOULD be used for display purposes in a wallet to decide how many
	// decimal places to show and accept when displaying or entering amounts.
	Decimals int8 `json:"decimals"`

	// Id The unique identifier assigned by the admin to the instrument.
	Id string `json:"id"`

	// Name The display name for the instrument recommended by the instrument admin. This is not necessarily unique.
	Name string `json:"name"`

	// SupportedApis Map from token standard API name to the minor version of the API supported, e.g.,
	// splice-api-token-metadata-v1 -> 1 where the `1` corresponds to the minor version.
	SupportedApis SupportedApis `json:"supportedApis"`

	// Symbol The symbol for the instrument recommended by the instrument admin. This is not necessarily unique.
	Symbol string `json:"symbol"`

	// TotalSupply Decimal encoded current total supply of the instrument.
	TotalSupply *string `json:"totalSupply,omitempty"`

	// TotalSupplyAsOf The timestamp when the total supply was last computed.
	TotalSupplyAsOf *time.Time `json:"totalSupplyAsOf,omitempty"`
}

// ListInstrumentsResponse defines model for ListInstrumentsResponse.
type ListInstrumentsResponse struct {
	Instruments []Instrument `json:"instruments"`

	// NextPageToken The token for the next page of results, to be used as the lastInstrumentId for the next page.
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// SupportedApis Map from token standard API name to the minor version of the API supported, e.g.,
// splice-api-token-metadata-v1 -> 1 where the `1` corresponds to the minor version.
type SupportedApis map[string]int32

// N404 defines model for 404.
type N404 = ErrorResponse

// N500 defines model for 500.
type N500 = ErrorResponse

// ListInstrumentsParams defines parameters for ListInstruments.
type ListInstrumentsParams struct {
	// PageSize Number of instruments per page.
	PageSize *int32 `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// PageToken The `nextPageToken` received from the response for the previous page.
	PageToken *string `form:"pageToken,omitempty" json:"pageToken,omitempty"`
}

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetRegistryInfo performs a GET /registry/metadata/v1/info (the `GetRegistryInfo` operationId) request.
	//
	// Get information about the registry.
	// The response includes the standards supported by the registry.
	GetRegistryInfo(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListInstruments performs a GET /registry/metadata/v1/instruments (the `ListInstruments` operationId) request.
	//
	// List all instruments managed by this instrument admin.
	ListInstruments(ctx context.Context, params *ListInstrumentsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetInstrument performs a GET /registry/metadata/v1/instruments/{instrumentId} (the `GetInstrument` operationId) request.
	//
	// Retrieve an instrument's metadata.
	GetInstrument(ctx context.Context, instrumentId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetRegistryInfo performs a GET /registry/metadata/v1/info (the `GetRegistryInfo` operationId) request.
//
// Get information about the registry.
// The response includes the standards supported by the registry.
func (c *Client) GetRegistryInfo(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRegistryInfoRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListInstruments performs a GET /registry/metadata/v1/instruments (the `ListInstruments` operationId) request.
//
// List all instruments managed by this instrument admin.
func (c *Client) ListInstruments(ctx context.Context, params *ListInstrumentsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListInstrumentsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetInstrument performs a GET /registry/metadata/v1/instruments/{instrumentId} (the `GetInstrument` operationId) request.
//
// Retrieve an instrument's metadata.
func (c *Client) GetInstrument(ctx context.Context, instrumentId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetInstrumentRequest(c.Server, instrumentId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetRegistryInfoRequest constructs an http.Request for the GetRegistryInfo method
func NewGetRegistryInfoRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/registry/metadata/v1/info")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListInstrumentsRequest constructs an http.Request for the ListInstruments method
func NewListInstrumentsRequest(server string, params *ListInstrumentsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/registry/metadata/v1/instruments")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "pageSize", *params.PageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PageToken != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "pageToken", *params.PageToken, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetInstrumentRequest constructs an http.Request for the GetInstrument method
func NewGetInstrumentRequest(server string, instrumentId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "instrumentId", instrumentId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/registry/metadata/v1/instruments/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetRegistryInfoWithResponse performs a GET /registry/metadata/v1/info (the `GetRegistryInfo` operationId) request.
	//
	// Get information about the registry.
	// The response includes the standards supported by the registry.
	//
	// Returns a wrapper object for the known response body format(s).
	GetRegistryInfoWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetRegistryInfoResp, error)

	// ListInstrumentsWithResponse performs a GET /registry/metadata/v1/instruments (the `ListInstruments` operationId) request.
	//
	// List all instruments managed by this instrument admin.
	//
	// Returns a wrapper object for the known response body format(s).
	ListInstrumentsWithResponse(ctx context.Context, params *ListInstrumentsParams, reqEditors ...RequestEditorFn) (*ListInstrumentsResp, error)

	// GetInstrumentWithResponse performs a GET /registry/metadata/v1/instruments/{instrumentId} (the `GetInstrument` operationId) request.
	//
	// Retrieve an instrument's metadata.
	//
	// Returns a wrapper object for the known response body format(s).
	GetInstrumentWithResponse(ctx context.Context, instrumentId string, reqEditors ...RequestEditorFn) (*GetInstrumentResp, error)
}

type GetRegistryInfoResp struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *GetRegistryInfoResponse
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *N404
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *N500
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetRegistryInfoResp) GetJSON200() *GetRegistryInfoResponse {
	return r.JSON200
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetRegistryInfoResp) GetJSON404() *N404 {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetRegistryInfoResp) GetJSON500() *N500 {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r GetRegistryInfoResp) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetRegistryInfoResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRegistryInfoResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetRegistryInfoResp) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListInstrumentsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ListInstrumentsResponse
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *N404
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *N500
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListInstrumentsResp) GetJSON200() *ListInstrumentsResponse {
	return r.JSON200
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r ListInstrumentsResp) GetJSON404() *N404 {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r ListInstrumentsResp) GetJSON500() *N500 {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r ListInstrumentsResp) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListInstrumentsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListInstrumentsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListInstrumentsResp) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetInstrumentResp struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Instrument
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *N404
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *N500
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetInstrumentResp) GetJSON200() *Instrument {
	return r.JSON200
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetInstrumentResp) GetJSON404() *N404 {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetInstrumentResp) GetJSON500() *N500 {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r GetInstrumentResp) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetInstrumentResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetInstrumentResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetInstrumentResp) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetRegistryInfoWithResponse performs a GET /registry/metadata/v1/info (the `GetRegistryInfo` operationId) request.
//
// Get information about the registry.
// The response includes the standards supported by the registry.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetRegistryInfoWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetRegistryInfoResp, error) {
	rsp, err := c.GetRegistryInfo(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRegistryInfoResp(rsp)
}

// ListInstrumentsWithResponse performs a GET /registry/metadata/v1/instruments (the `ListInstruments` operationId) request.
//
// List all instruments managed by this instrument admin.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) ListInstrumentsWithResponse(ctx context.Context, params *ListInstrumentsParams, reqEditors ...RequestEditorFn) (*ListInstrumentsResp, error) {
	rsp, err := c.ListInstruments(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListInstrumentsResp(rsp)
}

// GetInstrumentWithResponse performs a GET /registry/metadata/v1/instruments/{instrumentId} (the `GetInstrument` operationId) request.
//
// Retrieve an instrument's metadata.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetInstrumentWithResponse(ctx context.Context, instrumentId string, reqEditors ...RequestEditorFn) (*GetInstrumentResp, error) {
	rsp, err := c.GetInstrument(ctx, instrumentId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetInstrumentResp(rsp)
}

// ParseGetRegistryInfoResp parses an HTTP response from a GetRegistryInfoWithResponse call
func ParseGetRegistryInfoResp(rsp *http.Response) (*GetRegistryInfoResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRegistryInfoResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetRegistryInfoResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseListInstrumentsResp parses an HTTP response from a ListInstrumentsWithResponse call
func ParseListInstrumentsResp(rsp *http.Response) (*ListInstrumentsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListInstrumentsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListInstrumentsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetInstrumentResp parses an HTTP response from a GetInstrumentWithResponse call
func ParseGetInstrumentResp(rsp *http.Response) (*GetInstrumentResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetInstrumentResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Instrument
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /registry/metadata/v1/info)
	GetRegistryInfo(c *gin.Context)

	// (GET /registry/metadata/v1/instruments)
	ListInstruments(c *gin.Context, params ListInstrumentsParams)

	// (GET /registry/metadata/v1/instruments/{instrumentId})
	GetInstrument(c *gin.Context, instrumentId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetRegistryInfo operation middleware
func (siw *ServerInterfaceWrapper) GetRegistryInfo(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRegistryInfo(c)
}

// ListInstruments operation middleware
func (siw *ServerInterfaceWrapper) ListInstruments(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListInstrumentsParams

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageToken" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageToken", c.Request.URL.Query(), &params.PageToken, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageToken: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListInstruments(c, params)
}

// GetInstrument operation middleware
func (siw *ServerInterfaceWrapper) GetInstrument(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "instrumentId" -------------
	var instrumentId string

	err = runtime.BindStyledParameterWithOptions("simple", "instrumentId", c.Param("instrumentId"), &instrumentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter instrumentId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInstrument(c, instrumentId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/registry/metadata/v1/info", wrapper.GetRegistryInfo)
	router.GET(options.BaseURL+"/registry/metadata/v1/instruments", wrapper.ListInstruments)
	router.GET(options.BaseURL+"/registry/metadata/v1/instruments/:instrumentId", wrapper.GetInstrument)
}
