// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	"github.com/smartcontractkit/chainlink-canton/contracts"
)

// NewMockInstanceAddressFilter creates a new instance of MockInstanceAddressFilter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstanceAddressFilter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstanceAddressFilter {
	mock := &MockInstanceAddressFilter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInstanceAddressFilter is an autogenerated mock type for the InstanceAddressFilter type
type MockInstanceAddressFilter struct {
	mock.Mock
}

type MockInstanceAddressFilter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstanceAddressFilter) EXPECT() *MockInstanceAddressFilter_Expecter {
	return &MockInstanceAddressFilter_Expecter{mock: &_m.Mock}
}

// FilterContracts provides a mock function for the type MockInstanceAddressFilter
func (_mock *MockInstanceAddressFilter) FilterContracts(addresses []contracts.InstanceAddress) []contracts.InstanceAddress {
	ret := _mock.Called(addresses)

	if len(ret) == 0 {
		panic("no return value specified for FilterContracts")
	}

	var r0 []contracts.InstanceAddress
	if returnFunc, ok := ret.Get(0).(func([]contracts.InstanceAddress) []contracts.InstanceAddress); ok {
		r0 = returnFunc(addresses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]contracts.InstanceAddress)
		}
	}
	return r0
}

// MockInstanceAddressFilter_FilterContracts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterContracts'
type MockInstanceAddressFilter_FilterContracts_Call struct {
	*mock.Call
}

// FilterContracts is a helper method to define mock.On call
//   - addresses []contracts.InstanceAddress
func (_e *MockInstanceAddressFilter_Expecter) FilterContracts(addresses interface{}) *MockInstanceAddressFilter_FilterContracts_Call {
	return &MockInstanceAddressFilter_FilterContracts_Call{Call: _e.mock.On("FilterContracts", addresses)}
}

func (_c *MockInstanceAddressFilter_FilterContracts_Call) Run(run func(addresses []contracts.InstanceAddress)) *MockInstanceAddressFilter_FilterContracts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []contracts.InstanceAddress
		if args[0] != nil {
			arg0 = args[0].([]contracts.InstanceAddress)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInstanceAddressFilter_FilterContracts_Call) Return(instanceAddresss []contracts.InstanceAddress) *MockInstanceAddressFilter_FilterContracts_Call {
	_c.Call.Return(instanceAddresss)
	return _c
}

func (_c *MockInstanceAddressFilter_FilterContracts_Call) RunAndReturn(run func(addresses []contracts.InstanceAddress) []contracts.InstanceAddress) *MockInstanceAddressFilter_FilterContracts_Call {
	_c.Call.Return(run)
	return _c
}
