// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/digital-asset/dazl-client/v8/go/api/com/daml/ledger/api/v2"
	"github.com/smartcontractkit/go-daml/pkg/types"
	mock "github.com/stretchr/testify/mock"

	"github.com/smartcontractkit/chainlink-canton/bindings/generated/latest/splice/splice_api_token_holding_v1"
)

// NewMockInstrumentHoldingStore creates a new instance of MockInstrumentHoldingStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstrumentHoldingStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstrumentHoldingStore {
	mock := &MockInstrumentHoldingStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInstrumentHoldingStore is an autogenerated mock type for the InstrumentHoldingStoreInterface type
type MockInstrumentHoldingStore struct {
	mock.Mock
}

type MockInstrumentHoldingStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstrumentHoldingStore) EXPECT() *MockInstrumentHoldingStore_Expecter {
	return &MockInstrumentHoldingStore_Expecter{mock: &_m.Mock}
}

// GetHolding provides a mock function for the type MockInstrumentHoldingStore
func (_mock *MockInstrumentHoldingStore) GetHolding(party types.PARTY, instrumentId splice_api_token_holding_v1.InstrumentId) ([]*v2.ActiveContract, bool) {
	ret := _mock.Called(party, instrumentId)

	if len(ret) == 0 {
		panic("no return value specified for GetHolding")
	}

	var r0 []*v2.ActiveContract
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(types.PARTY, splice_api_token_holding_v1.InstrumentId) ([]*v2.ActiveContract, bool)); ok {
		return returnFunc(party, instrumentId)
	}
	if returnFunc, ok := ret.Get(0).(func(types.PARTY, splice_api_token_holding_v1.InstrumentId) []*v2.ActiveContract); ok {
		r0 = returnFunc(party, instrumentId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v2.ActiveContract)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(types.PARTY, splice_api_token_holding_v1.InstrumentId) bool); ok {
		r1 = returnFunc(party, instrumentId)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockInstrumentHoldingStore_GetHolding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHolding'
type MockInstrumentHoldingStore_GetHolding_Call struct {
	*mock.Call
}

// GetHolding is a helper method to define mock.On call
//   - party types.PARTY
//   - instrumentId splice_api_token_holding_v1.InstrumentId
func (_e *MockInstrumentHoldingStore_Expecter) GetHolding(party interface{}, instrumentId interface{}) *MockInstrumentHoldingStore_GetHolding_Call {
	return &MockInstrumentHoldingStore_GetHolding_Call{Call: _e.mock.On("GetHolding", party, instrumentId)}
}

func (_c *MockInstrumentHoldingStore_GetHolding_Call) Run(run func(party types.PARTY, instrumentId splice_api_token_holding_v1.InstrumentId)) *MockInstrumentHoldingStore_GetHolding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.PARTY
		if args[0] != nil {
			arg0 = args[0].(types.PARTY)
		}
		var arg1 splice_api_token_holding_v1.InstrumentId
		if args[1] != nil {
			arg1 = args[1].(splice_api_token_holding_v1.InstrumentId)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInstrumentHoldingStore_GetHolding_Call) Return(activeContracts []*v2.ActiveContract, b bool) *MockInstrumentHoldingStore_GetHolding_Call {
	_c.Call.Return(activeContracts, b)
	return _c
}

func (_c *MockInstrumentHoldingStore_GetHolding_Call) RunAndReturn(run func(party types.PARTY, instrumentId splice_api_token_holding_v1.InstrumentId) ([]*v2.ActiveContract, bool)) *MockInstrumentHoldingStore_GetHolding_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterParty provides a mock function for the type MockInstrumentHoldingStore
func (_mock *MockInstrumentHoldingStore) RegisterParty(parties ...string) {
	if len(parties) > 0 {
		_mock.Called(parties)
	} else {
		_mock.Called()
	}

	return
}

// MockInstrumentHoldingStore_RegisterParty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterParty'
type MockInstrumentHoldingStore_RegisterParty_Call struct {
	*mock.Call
}

// RegisterParty is a helper method to define mock.On call
//   - parties ...string
func (_e *MockInstrumentHoldingStore_Expecter) RegisterParty(parties ...interface{}) *MockInstrumentHoldingStore_RegisterParty_Call {
	return &MockInstrumentHoldingStore_RegisterParty_Call{Call: _e.mock.On("RegisterParty",
		append([]interface{}{}, parties...)...)}
}

func (_c *MockInstrumentHoldingStore_RegisterParty_Call) Run(run func(parties ...string)) *MockInstrumentHoldingStore_RegisterParty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		var variadicArgs []string
		if len(args) > 0 {
			variadicArgs = args[0].([]string)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockInstrumentHoldingStore_RegisterParty_Call) Return() *MockInstrumentHoldingStore_RegisterParty_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInstrumentHoldingStore_RegisterParty_Call) RunAndReturn(run func(parties ...string)) *MockInstrumentHoldingStore_RegisterParty_Call {
	_c.Run(run)
	return _c
}
