// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/digital-asset/dazl-client/v8/go/api/com/daml/ledger/api/v2"
	"github.com/smartcontractkit/go-daml/pkg/types"
	mock "github.com/stretchr/testify/mock"

	"github.com/smartcontractkit/chainlink-canton/contracts/v2"
	"github.com/smartcontractkit/chainlink-canton/eds/internal/store"
)

// NewMockActiveContractStore creates a new instance of MockActiveContractStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActiveContractStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActiveContractStore {
	mock := &MockActiveContractStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActiveContractStore is an autogenerated mock type for the ActiveContractStoreInterface type
type MockActiveContractStore struct {
	mock.Mock
}

type MockActiveContractStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActiveContractStore) EXPECT() *MockActiveContractStore_Expecter {
	return &MockActiveContractStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockActiveContractStore
func (_mock *MockActiveContractStore) Get(address contracts.InstanceAddress) (*v2.ActiveContract, bool) {
	ret := _mock.Called(address)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v2.ActiveContract
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(contracts.InstanceAddress) (*v2.ActiveContract, bool)); ok {
		return returnFunc(address)
	}
	if returnFunc, ok := ret.Get(0).(func(contracts.InstanceAddress) *v2.ActiveContract); ok {
		r0 = returnFunc(address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.ActiveContract)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(contracts.InstanceAddress) bool); ok {
		r1 = returnFunc(address)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockActiveContractStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockActiveContractStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - address contracts.InstanceAddress
func (_e *MockActiveContractStore_Expecter) Get(address interface{}) *MockActiveContractStore_Get_Call {
	return &MockActiveContractStore_Get_Call{Call: _e.mock.On("Get", address)}
}

func (_c *MockActiveContractStore_Get_Call) Run(run func(address contracts.InstanceAddress)) *MockActiveContractStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 contracts.InstanceAddress
		if args[0] != nil {
			arg0 = args[0].(contracts.InstanceAddress)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockActiveContractStore_Get_Call) Return(activeContract *v2.ActiveContract, b bool) *MockActiveContractStore_Get_Call {
	_c.Call.Return(activeContract, b)
	return _c
}

func (_c *MockActiveContractStore_Get_Call) RunAndReturn(run func(address contracts.InstanceAddress) (*v2.ActiveContract, bool)) *MockActiveContractStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByContractId provides a mock function for the type MockActiveContractStore
func (_mock *MockActiveContractStore) GetByContractId(contractId types.CONTRACT_ID) (*v2.ActiveContract, bool) {
	ret := _mock.Called(contractId)

	if len(ret) == 0 {
		panic("no return value specified for GetByContractId")
	}

	var r0 *v2.ActiveContract
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(types.CONTRACT_ID) (*v2.ActiveContract, bool)); ok {
		return returnFunc(contractId)
	}
	if returnFunc, ok := ret.Get(0).(func(types.CONTRACT_ID) *v2.ActiveContract); ok {
		r0 = returnFunc(contractId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.ActiveContract)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(types.CONTRACT_ID) bool); ok {
		r1 = returnFunc(contractId)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockActiveContractStore_GetByContractId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByContractId'
type MockActiveContractStore_GetByContractId_Call struct {
	*mock.Call
}

// GetByContractId is a helper method to define mock.On call
//   - contractId types.CONTRACT_ID
func (_e *MockActiveContractStore_Expecter) GetByContractId(contractId interface{}) *MockActiveContractStore_GetByContractId_Call {
	return &MockActiveContractStore_GetByContractId_Call{Call: _e.mock.On("GetByContractId", contractId)}
}

func (_c *MockActiveContractStore_GetByContractId_Call) Run(run func(contractId types.CONTRACT_ID)) *MockActiveContractStore_GetByContractId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.CONTRACT_ID
		if args[0] != nil {
			arg0 = args[0].(types.CONTRACT_ID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockActiveContractStore_GetByContractId_Call) Return(activeContract *v2.ActiveContract, b bool) *MockActiveContractStore_GetByContractId_Call {
	_c.Call.Return(activeContract, b)
	return _c
}

func (_c *MockActiveContractStore_GetByContractId_Call) RunAndReturn(run func(contractId types.CONTRACT_ID) (*v2.ActiveContract, bool)) *MockActiveContractStore_GetByContractId_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTemplateId provides a mock function for the type MockActiveContractStore
func (_mock *MockActiveContractStore) GetByTemplateId(party types.PARTY, templateId contracts.TemplateID) ([]*v2.ActiveContract, bool) {
	ret := _mock.Called(party, templateId)

	if len(ret) == 0 {
		panic("no return value specified for GetByTemplateId")
	}

	var r0 []*v2.ActiveContract
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(types.PARTY, contracts.TemplateID) ([]*v2.ActiveContract, bool)); ok {
		return returnFunc(party, templateId)
	}
	if returnFunc, ok := ret.Get(0).(func(types.PARTY, contracts.TemplateID) []*v2.ActiveContract); ok {
		r0 = returnFunc(party, templateId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v2.ActiveContract)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(types.PARTY, contracts.TemplateID) bool); ok {
		r1 = returnFunc(party, templateId)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockActiveContractStore_GetByTemplateId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTemplateId'
type MockActiveContractStore_GetByTemplateId_Call struct {
	*mock.Call
}

// GetByTemplateId is a helper method to define mock.On call
//   - party types.PARTY
//   - templateId contracts.TemplateID
func (_e *MockActiveContractStore_Expecter) GetByTemplateId(party interface{}, templateId interface{}) *MockActiveContractStore_GetByTemplateId_Call {
	return &MockActiveContractStore_GetByTemplateId_Call{Call: _e.mock.On("GetByTemplateId", party, templateId)}
}

func (_c *MockActiveContractStore_GetByTemplateId_Call) Run(run func(party types.PARTY, templateId contracts.TemplateID)) *MockActiveContractStore_GetByTemplateId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.PARTY
		if args[0] != nil {
			arg0 = args[0].(types.PARTY)
		}
		var arg1 contracts.TemplateID
		if args[1] != nil {
			arg1 = args[1].(contracts.TemplateID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActiveContractStore_GetByTemplateId_Call) Return(activeContracts []*v2.ActiveContract, b bool) *MockActiveContractStore_GetByTemplateId_Call {
	_c.Call.Return(activeContracts, b)
	return _c
}

func (_c *MockActiveContractStore_GetByTemplateId_Call) RunAndReturn(run func(party types.PARTY, templateId contracts.TemplateID) ([]*v2.ActiveContract, bool)) *MockActiveContractStore_GetByTemplateId_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterTemplates provides a mock function for the type MockActiveContractStore
func (_mock *MockActiveContractStore) RegisterTemplates(templates ...store.RegisteredTemplate) {
	if len(templates) > 0 {
		_mock.Called(templates)
	} else {
		_mock.Called()
	}

	return
}

// MockActiveContractStore_RegisterTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterTemplates'
type MockActiveContractStore_RegisterTemplates_Call struct {
	*mock.Call
}

// RegisterTemplates is a helper method to define mock.On call
//   - templates ...store.RegisteredTemplate
func (_e *MockActiveContractStore_Expecter) RegisterTemplates(templates ...interface{}) *MockActiveContractStore_RegisterTemplates_Call {
	return &MockActiveContractStore_RegisterTemplates_Call{Call: _e.mock.On("RegisterTemplates",
		append([]interface{}{}, templates...)...)}
}

func (_c *MockActiveContractStore_RegisterTemplates_Call) Run(run func(templates ...store.RegisteredTemplate)) *MockActiveContractStore_RegisterTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []store.RegisteredTemplate
		var variadicArgs []store.RegisteredTemplate
		if len(args) > 0 {
			variadicArgs = args[0].([]store.RegisteredTemplate)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockActiveContractStore_RegisterTemplates_Call) Return() *MockActiveContractStore_RegisterTemplates_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockActiveContractStore_RegisterTemplates_Call) RunAndReturn(run func(templates ...store.RegisteredTemplate)) *MockActiveContractStore_RegisterTemplates_Call {
	_c.Run(run)
	return _c
}
