// Package ccv provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package ccv

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	externalRef0 "github.com/smartcontractkit/chainlink-canton/eds/api/common"
)

// CCVExecuteRequest defines model for CCVExecuteRequest.
type CCVExecuteRequest struct {
	// EncodedMessage The CCIP message to be executed, encoded as a hex string.
	EncodedMessage string `json:"encodedMessage"`

	// Receiver The unique identifier of a party.
	//
	// Example: some-party::1220131b86f50178e6f7aabe62ef79e79b4964a526a1c557776409f448cbcd2406ce
	Receiver externalRef0.PartyId `json:"receiver"`
}

// CCVExecuteResponse defines model for CCVExecuteResponse.
type CCVExecuteResponse struct {
	// ContextData The context to be passed along to the verifier.
	ContextData map[string]interface{} `json:"contextData"`

	// ContractId The unique identifier of a contract.
	//
	// Example: 00929f6a675c128bb54bef77a8cad8d330badd4330cf71f6a19b596b01f4b66b2dca121220cd655ce27fae64bdf6a203fcd987727de81c3762e46b1882ce2c2fbf0a72c64f
	ContractId         externalRef0.ContractId          `json:"contractId"`
	DisclosedContracts []externalRef0.DisclosedContract `json:"disclosedContracts"`

	// InstanceAddress The InstanceAddress of a contract, the keccak256 hash of the RawInstanceAddress.
	//
	// Example: 0x9d24274102a5d2f57506d48dee1394e33f7cef9a9c0920ee714d6f4a216a21a9
	InstanceAddress externalRef0.InstanceAddress `json:"instanceAddress"`

	// RawInstanceAddress The raw InstanceAddress of a contract, in the form of "prefix@owner", where prefix is the InstanceId of the contract.
	//
	// Example: some-contract-fgtlw@ccipOwner::1220131b86f50178e6f7aabe62ef79e79b4964a526a1c557776409f448cbcd2406ce
	RawInstanceAddress externalRef0.RawInstanceAddress `json:"rawInstanceAddress"`
}

// CCVSendRequest defines model for CCVSendRequest.
type CCVSendRequest struct {
	// Message A message to be sent from Canton.
	Message externalRef0.Message `json:"message"`
}

// CCVSendResponse defines model for CCVSendResponse.
type CCVSendResponse struct {
	// ContextData The context to be passed along to the verifier.
	ContextData map[string]interface{} `json:"contextData"`

	// ContractId The unique identifier of a contract.
	//
	// Example: 00929f6a675c128bb54bef77a8cad8d330badd4330cf71f6a19b596b01f4b66b2dca121220cd655ce27fae64bdf6a203fcd987727de81c3762e46b1882ce2c2fbf0a72c64f
	ContractId         externalRef0.ContractId          `json:"contractId"`
	DisclosedContracts []externalRef0.DisclosedContract `json:"disclosedContracts"`

	// InstanceAddress The InstanceAddress of a contract, the keccak256 hash of the RawInstanceAddress.
	//
	// Example: 0x9d24274102a5d2f57506d48dee1394e33f7cef9a9c0920ee714d6f4a216a21a9
	InstanceAddress externalRef0.InstanceAddress `json:"instanceAddress"`

	// RawInstanceAddress The raw InstanceAddress of a contract, in the form of "prefix@owner", where prefix is the InstanceId of the contract.
	//
	// Example: some-contract-fgtlw@ccipOwner::1220131b86f50178e6f7aabe62ef79e79b4964a526a1c557776409f448cbcd2406ce
	RawInstanceAddress externalRef0.RawInstanceAddress `json:"rawInstanceAddress"`
}

// PostCCVExecuteJSONRequestBody defines body for PostCCVExecute for application/json ContentType.
type PostCCVExecuteJSONRequestBody = CCVExecuteRequest

// PostCCVSendJSONRequestBody defines body for PostCCVSend for application/json ContentType.
type PostCCVSendJSONRequestBody = CCVSendRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// PostCCVExecuteWithBody performs a POST /ccip/v1/external/ccv/{address}/execute (the `PostCCVExecute` operationId) request,
	// with any type of body and a specified content type.
	//
	// Get the explicit disclosures for executing a message using this Cross-Chain-Verifier.
	PostCCVExecuteWithBody(ctx context.Context, address string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostCCVExecute performs a POST /ccip/v1/external/ccv/{address}/execute (the `PostCCVExecute` operationId) request.
	// Takes a body of the `application/json` content type.
	//
	// Get the explicit disclosures for executing a message using this Cross-Chain-Verifier.
	PostCCVExecute(ctx context.Context, address string, body PostCCVExecuteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostCCVSendWithBody performs a POST /ccip/v1/external/ccv/{address}/send (the `PostCCVSend` operationId) request,
	// with any type of body and a specified content type.
	//
	// Get the explicit disclosures for sending a message using this Cross-Chain-Verifier.
	PostCCVSendWithBody(ctx context.Context, address string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostCCVSend performs a POST /ccip/v1/external/ccv/{address}/send (the `PostCCVSend` operationId) request.
	// Takes a body of the `application/json` content type.
	//
	// Get the explicit disclosures for sending a message using this Cross-Chain-Verifier.
	PostCCVSend(ctx context.Context, address string, body PostCCVSendJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// PostCCVExecuteWithBody performs a POST /ccip/v1/external/ccv/{address}/execute (the `PostCCVExecute` operationId) request,
// with any type of body and a specified content type.
//
// Get the explicit disclosures for executing a message using this Cross-Chain-Verifier.
func (c *Client) PostCCVExecuteWithBody(ctx context.Context, address string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCCVExecuteRequestWithBody(c.Server, address, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostCCVExecute performs a POST /ccip/v1/external/ccv/{address}/execute (the `PostCCVExecute` operationId) request.
// Takes a body of the `application/json` content type.
//
// Get the explicit disclosures for executing a message using this Cross-Chain-Verifier.
func (c *Client) PostCCVExecute(ctx context.Context, address string, body PostCCVExecuteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCCVExecuteRequest(c.Server, address, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostCCVSendWithBody performs a POST /ccip/v1/external/ccv/{address}/send (the `PostCCVSend` operationId) request,
// with any type of body and a specified content type.
//
// Get the explicit disclosures for sending a message using this Cross-Chain-Verifier.
func (c *Client) PostCCVSendWithBody(ctx context.Context, address string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCCVSendRequestWithBody(c.Server, address, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostCCVSend performs a POST /ccip/v1/external/ccv/{address}/send (the `PostCCVSend` operationId) request.
// Takes a body of the `application/json` content type.
//
// Get the explicit disclosures for sending a message using this Cross-Chain-Verifier.
func (c *Client) PostCCVSend(ctx context.Context, address string, body PostCCVSendJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCCVSendRequest(c.Server, address, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostCCVExecuteRequest calls the generic PostCCVExecute builder with application/json body
func NewPostCCVExecuteRequest(server string, address string, body PostCCVExecuteJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostCCVExecuteRequestWithBody(server, address, "application/json", bodyReader)
}

// NewPostCCVExecuteRequestWithBody constructs an http.Request for the PostCCVExecute method, with any body, and a specified content type
func NewPostCCVExecuteRequestWithBody(server string, address string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "address", address, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ccip/v1/external/ccv/%s/execute", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostCCVSendRequest calls the generic PostCCVSend builder with application/json body
func NewPostCCVSendRequest(server string, address string, body PostCCVSendJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostCCVSendRequestWithBody(server, address, "application/json", bodyReader)
}

// NewPostCCVSendRequestWithBody constructs an http.Request for the PostCCVSend method, with any body, and a specified content type
func NewPostCCVSendRequestWithBody(server string, address string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "address", address, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ccip/v1/external/ccv/%s/send", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// PostCCVExecuteWithBodyWithResponse performs a POST /ccip/v1/external/ccv/{address}/execute (the `PostCCVExecute` operationId) request,
	// with any type of body and a specified content type.
	//
	// Get the explicit disclosures for executing a message using this Cross-Chain-Verifier.
	//
	// Returns a wrapper object for the known response body format(s).
	PostCCVExecuteWithBodyWithResponse(ctx context.Context, address string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCCVExecuteResponse, error)

	// PostCCVExecuteWithResponse performs a POST /ccip/v1/external/ccv/{address}/execute (the `PostCCVExecute` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Get the explicit disclosures for executing a message using this Cross-Chain-Verifier.
	PostCCVExecuteWithResponse(ctx context.Context, address string, body PostCCVExecuteJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCCVExecuteResponse, error)

	// PostCCVSendWithBodyWithResponse performs a POST /ccip/v1/external/ccv/{address}/send (the `PostCCVSend` operationId) request,
	// with any type of body and a specified content type.
	//
	// Get the explicit disclosures for sending a message using this Cross-Chain-Verifier.
	//
	// Returns a wrapper object for the known response body format(s).
	PostCCVSendWithBodyWithResponse(ctx context.Context, address string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCCVSendResponse, error)

	// PostCCVSendWithResponse performs a POST /ccip/v1/external/ccv/{address}/send (the `PostCCVSend` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Get the explicit disclosures for sending a message using this Cross-Chain-Verifier.
	PostCCVSendWithResponse(ctx context.Context, address string, body PostCCVSendJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCCVSendResponse, error)
}

type PostCCVExecuteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *CCVExecuteResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *externalRef0.N400
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *externalRef0.N404
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *externalRef0.N500
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostCCVExecuteResponse) GetJSON200() *CCVExecuteResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r PostCCVExecuteResponse) GetJSON400() *externalRef0.N400 {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r PostCCVExecuteResponse) GetJSON404() *externalRef0.N404 {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r PostCCVExecuteResponse) GetJSON500() *externalRef0.N500 {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r PostCCVExecuteResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostCCVExecuteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostCCVExecuteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostCCVExecuteResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostCCVSendResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *CCVSendResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *externalRef0.N400
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *externalRef0.N404
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *externalRef0.N500
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostCCVSendResponse) GetJSON200() *CCVSendResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r PostCCVSendResponse) GetJSON400() *externalRef0.N400 {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r PostCCVSendResponse) GetJSON404() *externalRef0.N404 {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r PostCCVSendResponse) GetJSON500() *externalRef0.N500 {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r PostCCVSendResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostCCVSendResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostCCVSendResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostCCVSendResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// PostCCVExecuteWithBodyWithResponse performs a POST /ccip/v1/external/ccv/{address}/execute (the `PostCCVExecute` operationId) request,
// with any type of body and a specified content type.
//
// Get the explicit disclosures for executing a message using this Cross-Chain-Verifier.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) PostCCVExecuteWithBodyWithResponse(ctx context.Context, address string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCCVExecuteResponse, error) {
	rsp, err := c.PostCCVExecuteWithBody(ctx, address, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCCVExecuteResponse(rsp)
}

// PostCCVExecuteWithResponse performs a POST /ccip/v1/external/ccv/{address}/execute (the `PostCCVExecute` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Get the explicit disclosures for executing a message using this Cross-Chain-Verifier.
func (c *ClientWithResponses) PostCCVExecuteWithResponse(ctx context.Context, address string, body PostCCVExecuteJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCCVExecuteResponse, error) {
	rsp, err := c.PostCCVExecute(ctx, address, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCCVExecuteResponse(rsp)
}

// PostCCVSendWithBodyWithResponse performs a POST /ccip/v1/external/ccv/{address}/send (the `PostCCVSend` operationId) request,
// with any type of body and a specified content type.
//
// Get the explicit disclosures for sending a message using this Cross-Chain-Verifier.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) PostCCVSendWithBodyWithResponse(ctx context.Context, address string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCCVSendResponse, error) {
	rsp, err := c.PostCCVSendWithBody(ctx, address, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCCVSendResponse(rsp)
}

// PostCCVSendWithResponse performs a POST /ccip/v1/external/ccv/{address}/send (the `PostCCVSend` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Get the explicit disclosures for sending a message using this Cross-Chain-Verifier.
func (c *ClientWithResponses) PostCCVSendWithResponse(ctx context.Context, address string, body PostCCVSendJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCCVSendResponse, error) {
	rsp, err := c.PostCCVSend(ctx, address, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCCVSendResponse(rsp)
}

// ParsePostCCVExecuteResponse parses an HTTP response from a PostCCVExecuteWithResponse call
func ParsePostCCVExecuteResponse(rsp *http.Response) (*PostCCVExecuteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostCCVExecuteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CCVExecuteResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostCCVSendResponse parses an HTTP response from a PostCCVSendWithResponse call
func ParsePostCCVSendResponse(rsp *http.Response) (*PostCCVSendResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostCCVSendResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CCVSendResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /ccip/v1/external/ccv/{address}/execute)
	PostCCVExecute(c *gin.Context, address string)

	// (POST /ccip/v1/external/ccv/{address}/send)
	PostCCVSend(c *gin.Context, address string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostCCVExecute operation middleware
func (siw *ServerInterfaceWrapper) PostCCVExecute(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "address" -------------
	var address string

	err = runtime.BindStyledParameterWithOptions("simple", "address", c.Param("address"), &address, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter address: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostCCVExecute(c, address)
}

// PostCCVSend operation middleware
func (siw *ServerInterfaceWrapper) PostCCVSend(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "address" -------------
	var address string

	err = runtime.BindStyledParameterWithOptions("simple", "address", c.Param("address"), &address, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter address: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostCCVSend(c, address)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/ccip/v1/external/ccv/:address/send", wrapper.PostCCVSend)
	router.POST(options.BaseURL+"/ccip/v1/external/ccv/:address/execute", wrapper.PostCCVExecute)
}
