version: "3.3"
name: swagger-ui
services:

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "80:8080"
    volumes:
      - .:/usr/share/nginx/html/openapi
    environment:
      URLS: "[
          {url: '/openapi/scan-proxy.yaml', name: 'Scan Proxy'},
          {url: '/openapi/token-metadata-v1.yaml', name: 'Token Metadata V1'},
          {url: '/openapi/transfer-instruction-v1.yaml', name: 'Transfer Instruction V1'},
          {url: '/openapi/daRegistry/da-registry-backend-api.yaml', name: 'DA Registry Backend API'}
        ]"