openapi: 3.0.0
info:
  title: CCIP Explicit Disclosure API
  description: Provides access to explicit disclosures required to send/execute CCIP messages from/to Canton.
  version: 1.0.0

paths:
  /ccip/v1/message/send:
    post:
      operationId: ccipSend
      description: |
        Get the explicit disclosure for sending a CCIP message to Canton.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CCIPSendRequest'
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CCIPSendResponse'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /ccip/v1/message/execute:
    post:
      operationId: ccipExecute
      description: |
        Get the explicit disclosure for executing a CCIP message on Canton.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CCIPExecuteRequest'
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CCIPExecuteResponse'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /ccip/v1/perPartyRouter/factory:
    post:
      operationId: perPartyRouterFactory
      description: |
        Get the explicit disclosures for instantiating a PerPartyRouter using the PerPartyRouterFactory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CCIPPerPartyRouterFactoryRequest'
      responses: 
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CCIPPerPartyRouterFactoryResponse'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /ccip/v1/disclosure/{instanceAddress}:
    get:
      operationId: getDisclosure
      description: |
        Get the explicit disclosure for a given contract, identified by its InstanceAddress.
      parameters:
        - name: instanceAddress
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DisclosedContract'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

components:
  responses:
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    '500':
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    CCIPSendRequest:
      type: object
      required:
        - ccvs
      properties:
        ccvs:
          type: array
          items:
            type: string
          description: |
            The list of InstanceAddresses for all CCVs which should verify the message.
            As part of the response, the explicit disclosures for all CCVs that this EDS knows about will be returned.
    CCIPSendResponse:
      type: object
      required:
        - choiceContext
        - ccvs
      properties:
        choiceContext:
          $ref: '#/components/schemas/ChoiceContext'
        ccvs:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/OptionalDisclosure'

    CCIPExecuteRequest:
        type: object
        required:
          - encodedMessage
          - ccvs
        properties:
          encodedMessage:
            type: string
            description: The encoded CCIP message to be executed, in hex format.
          ccvs:
            type: array
            items:
              type: string
            description: |
              The list of InstanceAddresses for all CCVs which should verify the message.
              As part of the response, the explicit disclosures for all CCVs that this EDS knows about will be returned.
    CCIPExecuteResponse:
      type: object
      required:
        - choiceContext
        - poolExtraContext
        - ccvs
      properties:
        choiceContext:
          $ref: '#/components/schemas/ChoiceContext'
        poolExtraContext:
          type: object
          description: |
            The additional data to use when exercising the choice for the token pool. 
            Will be empty if no token transfer is part of the message.
        ccvs:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/OptionalDisclosure'
        tokenPool:
          allOf:
            - $ref: '#/components/schemas/DisclosedContract'
          nullable: true
          description: |
            The explicit disclosure for the token pool.
            Only present if a token transfer is part of the message.
        tokenPoolHoldings:
          allOf:
            - $ref: '#/components/schemas/DisclosedContract'
          nullable: true
          description: |
            The explicit disclosures for the token pool holdings.
            Only present if a token transfer is part of the message.

    CCIPPerPartyRouterFactoryRequest:
      type: object
      required:
        - partyID
      properties:
        partyID:
          type: string
    CCIPPerPartyRouterFactoryResponse:
      type: object
      required:
        - perPartyRouterFactoryId
        - disclosedContracts
      properties:
        perPartyRouterFactoryId:
          type: string
          description: The Contract ID of the PerPartyRouterFactory
        disclosedContracts:
          description: Disclosures for all contracts required for the caller to instantiate a PerPartyRouter
          type: array
          items:
            $ref: '#/components/schemas/DisclosedContract'

    ChoiceContext:
      description: |
        The context required to send/execute a message from/to Canton.
        Used to retrieve additional CCIP contracts which are referred to via their
        contract IDs in the 'choiceContextData'.
      type: object
      required:
        - choiceContextData
        - disclosedContracts
      properties:
        choiceContextData:
          description: The additional data to use when exercising the choice.
          type: object
        disclosedContracts:
          description: |
              The contracts which are explicitly disclosed as part of the choice context.
              These contracts are required to be disclosed in order to send/execute a message from/to Canton.
          type: array
          items:
            $ref: '#/components/schemas/DisclosedContract'

    OptionalDisclosure:
      type: object
      description: |
        The result of the explicit disclosure lookup for a contract.
        Will be used in places where the EDS is not guaranteed to serve the explicit disclosure itself:
        - If the EDS can serve an explicit disclosure for the requested contract, then the 'disclosedContract' field will be returned, containing the explicit disclosure for the contract.
        - If the contract's owner has registered the contract with the global EDS registry, but the EDS cannot serve an explicit disclosure for the contract itself, then the 'registeredContract' field will be returned, containing the information on where to query the explicit disclosure for the contract, as well as the party ID of the owner of the contract.
      properties:
        disclosedContract:
          $ref: '#/components/schemas/DisclosedContract'
        registeredContract:
          $ref: '#/components/schemas/RegisteredContract'


    DisclosedContract:
      type: object
      required:
        - templateId
        - contractId
        - createdEventBlob
        - synchronizerId
      properties:
        templateId:
          type: string
        contractId:
          type: string
        createdEventBlob:
          type: string
        synchronizerId:
          description: The synchronizer to which the contract is currently assigned.
          type: string

    RegisteredContract:
      type: object
      description: |
        If the contract has been registered with the global EDS registry, then this object will be returned.
        It contains the information on where to query the explicit disclosure for the contract, as well as the party ID of the owner of the contract.
      required:
        - owner
        - edsURL
      properties:
        owner:
          type: string
          description: The party ID of the owner of the contract.
        edsURL:
          type: string
          description: The URL of the EDS that can be used to query an explicit disclosure for the contract.

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
        details:
          type: string
