// Package ccip provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package ccip

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	externalRef0 "github.com/smartcontractkit/chainlink-canton/eds/api/common"
)

// CCIPExecuteRequest defines model for CCIPExecuteRequest.
type CCIPExecuteRequest struct {
	// EncodedMessage The CCIP message to be executed, encoded as a hex string.
	EncodedMessage string `json:"encodedMessage"`

	// Receiver The unique identifier of a party.
	//
	// Example: some-party::1220131b86f50178e6f7aabe62ef79e79b4964a526a1c557776409f448cbcd2406ce
	Receiver externalRef0.PartyId `json:"receiver"`
}

// CCIPExecuteResponse defines model for CCIPExecuteResponse.
type CCIPExecuteResponse struct {
	// ContextData The context to be passed along to CCIP.
	ContextData        map[string]interface{}           `json:"contextData"`
	DisclosedContracts []externalRef0.DisclosedContract `json:"disclosedContracts"`

	// TokenPool The raw InstanceAddress of a contract, in the form of "prefix@owner", where prefix is the InstanceId of the contract.
	//
	// Example: some-contract-fgtlw@ccipOwner::1220131b86f50178e6f7aabe62ef79e79b4964a526a1c557776409f448cbcd2406ce
	TokenPool *externalRef0.RawInstanceAddress `json:"tokenPool,omitempty"`
}

// CCIPPerPartyRouterFactoryRequest defines model for CCIPPerPartyRouterFactoryRequest.
type CCIPPerPartyRouterFactoryRequest struct {
	// PartyID The unique identifier of a party.
	//
	// Example: some-party::1220131b86f50178e6f7aabe62ef79e79b4964a526a1c557776409f448cbcd2406ce
	PartyID externalRef0.PartyId `json:"partyID"`
}

// CCIPPerPartyRouterFactoryResponse defines model for CCIPPerPartyRouterFactoryResponse.
type CCIPPerPartyRouterFactoryResponse struct {
	// ContractId The unique identifier of a contract.
	//
	// Example: 00929f6a675c128bb54bef77a8cad8d330badd4330cf71f6a19b596b01f4b66b2dca121220cd655ce27fae64bdf6a203fcd987727de81c3762e46b1882ce2c2fbf0a72c64f
	ContractId externalRef0.ContractId `json:"contractId"`

	// DisclosedContracts Disclosures for all contracts required for the caller to instantiate a PerPartyRouter
	DisclosedContracts []externalRef0.DisclosedContract `json:"disclosedContracts"`

	// InstanceAddress The InstanceAddress of a contract, the keccak256 hash of the RawInstanceAddress.
	//
	// Example: 0x9d24274102a5d2f57506d48dee1394e33f7cef9a9c0920ee714d6f4a216a21a9
	InstanceAddress externalRef0.InstanceAddress `json:"instanceAddress"`

	// RawInstanceAddress The raw InstanceAddress of a contract, in the form of "prefix@owner", where prefix is the InstanceId of the contract.
	//
	// Example: some-contract-fgtlw@ccipOwner::1220131b86f50178e6f7aabe62ef79e79b4964a526a1c557776409f448cbcd2406ce
	RawInstanceAddress externalRef0.RawInstanceAddress `json:"rawInstanceAddress"`
}

// CCIPSendRequest defines model for CCIPSendRequest.
type CCIPSendRequest struct {
	// Message A message to be sent from Canton.
	Message               externalRef0.Message               `json:"message"`
	SenderRequiredCCVs    *[]externalRef0.RawOrHashedAddress `json:"senderRequiredCCVs,omitempty"`
	TokenPoolRequiredCCVs *[]externalRef0.RawOrHashedAddress `json:"tokenPoolRequiredCCVs,omitempty"`
}

// CCIPSendResponse defines model for CCIPSendResponse.
type CCIPSendResponse struct {
	// Ccvs A list of requested CCVs containing their addresses.
	// If default CCVs apply, this list might contain more CCVs than originally requested.
	//
	//
	// Example: ["committeeverifier-abcde@ccipOwner::1220131b86f50178e6f7aabe62ef79e79b4964a526a1c557776409f448cbcd2406ce","0x4bed5af0e77b4d7a552a1f933b13c275bbdc231b8499b2e14edcc634a6869a5f"]
	Ccvs []externalRef0.RawOrHashedAddress `json:"ccvs"`

	// ContextData The context to be passed along to CCIP.
	ContextData        map[string]interface{}           `json:"contextData"`
	DisclosedContracts []externalRef0.DisclosedContract `json:"disclosedContracts"`

	// Executor An address which can be either a RawInstanceAddress or an InstanceAddress.
	Executor *externalRef0.RawOrHashedAddress `json:"executor,omitempty"`

	// FeeTokenConfigCid TokenConfig contract ID for the message fee token.
	FeeTokenConfigCid string `json:"feeTokenConfigCid"`
}

// LookupTokenPoolResponse defines model for LookupTokenPoolResponse.
type LookupTokenPoolResponse struct {
	// RawInstanceAddress The raw InstanceAddress of a contract, in the form of "prefix@owner", where prefix is the InstanceId of the contract.
	//
	// Example: some-contract-fgtlw@ccipOwner::1220131b86f50178e6f7aabe62ef79e79b4964a526a1c557776409f448cbcd2406ce
	RawInstanceAddress externalRef0.RawInstanceAddress `json:"rawInstanceAddress"`
}

// PostPerPartyRouterFactoryJSONRequestBody defines body for PostPerPartyRouterFactory for application/json ContentType.
type PostPerPartyRouterFactoryJSONRequestBody = CCIPPerPartyRouterFactoryRequest

// PostCCIPExecuteJSONRequestBody defines body for PostCCIPExecute for application/json ContentType.
type PostCCIPExecuteJSONRequestBody = CCIPExecuteRequest

// PostCCIPSendJSONRequestBody defines body for PostCCIPSend for application/json ContentType.
type PostCCIPSendJSONRequestBody = CCIPSendRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// PostPerPartyRouterFactoryWithBody performs a POST /ccip/v1/global/PerPartyRouter/factory (the `PostPerPartyRouterFactory` operationId) request,
	// with any type of body and a specified content type.
	//
	// Get the explicit disclosures for instantiating a PerPartyRouter using the PerPartyRouterFactory.
	PostPerPartyRouterFactoryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostPerPartyRouterFactory performs a POST /ccip/v1/global/PerPartyRouter/factory (the `PostPerPartyRouterFactory` operationId) request.
	// Takes a body of the `application/json` content type.
	//
	// Get the explicit disclosures for instantiating a PerPartyRouter using the PerPartyRouterFactory.
	PostPerPartyRouterFactory(ctx context.Context, body PostPerPartyRouterFactoryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTokenAdminRegistryToken performs a GET /ccip/v1/global/TokenAdminRegistry/token/{instrumentId} (the `GetTokenAdminRegistryToken` operationId) request.
	//
	// Get the token pool for a given instrument from the token admin registry.
	GetTokenAdminRegistryToken(ctx context.Context, instrumentId externalRef0.HashedInstrumentId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostCCIPExecuteWithBody performs a POST /ccip/v1/global/message/execute (the `PostCCIPExecute` operationId) request,
	// with any type of body and a specified content type.
	//
	// Get the explicit disclosures for executing a CCIP message on Canton.
	PostCCIPExecuteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostCCIPExecute performs a POST /ccip/v1/global/message/execute (the `PostCCIPExecute` operationId) request.
	// Takes a body of the `application/json` content type.
	//
	// Get the explicit disclosures for executing a CCIP message on Canton.
	PostCCIPExecute(ctx context.Context, body PostCCIPExecuteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostCCIPSendWithBody performs a POST /ccip/v1/global/message/send (the `PostCCIPSend` operationId) request,
	// with any type of body and a specified content type.
	//
	// Get the explicit disclosure for sending a CCIP message from Canton.
	PostCCIPSendWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostCCIPSend performs a POST /ccip/v1/global/message/send (the `PostCCIPSend` operationId) request.
	// Takes a body of the `application/json` content type.
	//
	// Get the explicit disclosure for sending a CCIP message from Canton.
	PostCCIPSend(ctx context.Context, body PostCCIPSendJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// PostPerPartyRouterFactoryWithBody performs a POST /ccip/v1/global/PerPartyRouter/factory (the `PostPerPartyRouterFactory` operationId) request,
// with any type of body and a specified content type.
//
// Get the explicit disclosures for instantiating a PerPartyRouter using the PerPartyRouterFactory.
func (c *Client) PostPerPartyRouterFactoryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPerPartyRouterFactoryRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostPerPartyRouterFactory performs a POST /ccip/v1/global/PerPartyRouter/factory (the `PostPerPartyRouterFactory` operationId) request.
// Takes a body of the `application/json` content type.
//
// Get the explicit disclosures for instantiating a PerPartyRouter using the PerPartyRouterFactory.
func (c *Client) PostPerPartyRouterFactory(ctx context.Context, body PostPerPartyRouterFactoryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPerPartyRouterFactoryRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetTokenAdminRegistryToken performs a GET /ccip/v1/global/TokenAdminRegistry/token/{instrumentId} (the `GetTokenAdminRegistryToken` operationId) request.
//
// Get the token pool for a given instrument from the token admin registry.
func (c *Client) GetTokenAdminRegistryToken(ctx context.Context, instrumentId externalRef0.HashedInstrumentId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTokenAdminRegistryTokenRequest(c.Server, instrumentId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostCCIPExecuteWithBody performs a POST /ccip/v1/global/message/execute (the `PostCCIPExecute` operationId) request,
// with any type of body and a specified content type.
//
// Get the explicit disclosures for executing a CCIP message on Canton.
func (c *Client) PostCCIPExecuteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCCIPExecuteRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostCCIPExecute performs a POST /ccip/v1/global/message/execute (the `PostCCIPExecute` operationId) request.
// Takes a body of the `application/json` content type.
//
// Get the explicit disclosures for executing a CCIP message on Canton.
func (c *Client) PostCCIPExecute(ctx context.Context, body PostCCIPExecuteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCCIPExecuteRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostCCIPSendWithBody performs a POST /ccip/v1/global/message/send (the `PostCCIPSend` operationId) request,
// with any type of body and a specified content type.
//
// Get the explicit disclosure for sending a CCIP message from Canton.
func (c *Client) PostCCIPSendWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCCIPSendRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostCCIPSend performs a POST /ccip/v1/global/message/send (the `PostCCIPSend` operationId) request.
// Takes a body of the `application/json` content type.
//
// Get the explicit disclosure for sending a CCIP message from Canton.
func (c *Client) PostCCIPSend(ctx context.Context, body PostCCIPSendJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCCIPSendRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostPerPartyRouterFactoryRequest calls the generic PostPerPartyRouterFactory builder with application/json body
func NewPostPerPartyRouterFactoryRequest(server string, body PostPerPartyRouterFactoryJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostPerPartyRouterFactoryRequestWithBody(server, "application/json", bodyReader)
}

// NewPostPerPartyRouterFactoryRequestWithBody constructs an http.Request for the PostPerPartyRouterFactory method, with any body, and a specified content type
func NewPostPerPartyRouterFactoryRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ccip/v1/global/PerPartyRouter/factory")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetTokenAdminRegistryTokenRequest constructs an http.Request for the GetTokenAdminRegistryToken method
func NewGetTokenAdminRegistryTokenRequest(server string, instrumentId externalRef0.HashedInstrumentId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "instrumentId", instrumentId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ccip/v1/global/TokenAdminRegistry/token/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostCCIPExecuteRequest calls the generic PostCCIPExecute builder with application/json body
func NewPostCCIPExecuteRequest(server string, body PostCCIPExecuteJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostCCIPExecuteRequestWithBody(server, "application/json", bodyReader)
}

// NewPostCCIPExecuteRequestWithBody constructs an http.Request for the PostCCIPExecute method, with any body, and a specified content type
func NewPostCCIPExecuteRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ccip/v1/global/message/execute")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostCCIPSendRequest calls the generic PostCCIPSend builder with application/json body
func NewPostCCIPSendRequest(server string, body PostCCIPSendJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostCCIPSendRequestWithBody(server, "application/json", bodyReader)
}

// NewPostCCIPSendRequestWithBody constructs an http.Request for the PostCCIPSend method, with any body, and a specified content type
func NewPostCCIPSendRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ccip/v1/global/message/send")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// PostPerPartyRouterFactoryWithBodyWithResponse performs a POST /ccip/v1/global/PerPartyRouter/factory (the `PostPerPartyRouterFactory` operationId) request,
	// with any type of body and a specified content type.
	//
	// Get the explicit disclosures for instantiating a PerPartyRouter using the PerPartyRouterFactory.
	//
	// Returns a wrapper object for the known response body format(s).
	PostPerPartyRouterFactoryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPerPartyRouterFactoryResponse, error)

	// PostPerPartyRouterFactoryWithResponse performs a POST /ccip/v1/global/PerPartyRouter/factory (the `PostPerPartyRouterFactory` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Get the explicit disclosures for instantiating a PerPartyRouter using the PerPartyRouterFactory.
	PostPerPartyRouterFactoryWithResponse(ctx context.Context, body PostPerPartyRouterFactoryJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPerPartyRouterFactoryResponse, error)

	// GetTokenAdminRegistryTokenWithResponse performs a GET /ccip/v1/global/TokenAdminRegistry/token/{instrumentId} (the `GetTokenAdminRegistryToken` operationId) request.
	//
	// Get the token pool for a given instrument from the token admin registry.
	//
	// Returns a wrapper object for the known response body format(s).
	GetTokenAdminRegistryTokenWithResponse(ctx context.Context, instrumentId externalRef0.HashedInstrumentId, reqEditors ...RequestEditorFn) (*GetTokenAdminRegistryTokenResponse, error)

	// PostCCIPExecuteWithBodyWithResponse performs a POST /ccip/v1/global/message/execute (the `PostCCIPExecute` operationId) request,
	// with any type of body and a specified content type.
	//
	// Get the explicit disclosures for executing a CCIP message on Canton.
	//
	// Returns a wrapper object for the known response body format(s).
	PostCCIPExecuteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCCIPExecuteResponse, error)

	// PostCCIPExecuteWithResponse performs a POST /ccip/v1/global/message/execute (the `PostCCIPExecute` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Get the explicit disclosures for executing a CCIP message on Canton.
	PostCCIPExecuteWithResponse(ctx context.Context, body PostCCIPExecuteJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCCIPExecuteResponse, error)

	// PostCCIPSendWithBodyWithResponse performs a POST /ccip/v1/global/message/send (the `PostCCIPSend` operationId) request,
	// with any type of body and a specified content type.
	//
	// Get the explicit disclosure for sending a CCIP message from Canton.
	//
	// Returns a wrapper object for the known response body format(s).
	PostCCIPSendWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCCIPSendResponse, error)

	// PostCCIPSendWithResponse performs a POST /ccip/v1/global/message/send (the `PostCCIPSend` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Get the explicit disclosure for sending a CCIP message from Canton.
	PostCCIPSendWithResponse(ctx context.Context, body PostCCIPSendJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCCIPSendResponse, error)
}

type PostPerPartyRouterFactoryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *CCIPPerPartyRouterFactoryResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *externalRef0.N400
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *externalRef0.N404
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *externalRef0.N500
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostPerPartyRouterFactoryResponse) GetJSON200() *CCIPPerPartyRouterFactoryResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r PostPerPartyRouterFactoryResponse) GetJSON400() *externalRef0.N400 {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r PostPerPartyRouterFactoryResponse) GetJSON404() *externalRef0.N404 {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r PostPerPartyRouterFactoryResponse) GetJSON500() *externalRef0.N500 {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r PostPerPartyRouterFactoryResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostPerPartyRouterFactoryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostPerPartyRouterFactoryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostPerPartyRouterFactoryResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetTokenAdminRegistryTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *LookupTokenPoolResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *externalRef0.N400
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *externalRef0.N404
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *externalRef0.N500
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetTokenAdminRegistryTokenResponse) GetJSON200() *LookupTokenPoolResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetTokenAdminRegistryTokenResponse) GetJSON400() *externalRef0.N400 {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetTokenAdminRegistryTokenResponse) GetJSON404() *externalRef0.N404 {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetTokenAdminRegistryTokenResponse) GetJSON500() *externalRef0.N500 {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r GetTokenAdminRegistryTokenResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetTokenAdminRegistryTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTokenAdminRegistryTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetTokenAdminRegistryTokenResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostCCIPExecuteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *CCIPExecuteResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *externalRef0.N400
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *externalRef0.N404
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *externalRef0.N500
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostCCIPExecuteResponse) GetJSON200() *CCIPExecuteResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r PostCCIPExecuteResponse) GetJSON400() *externalRef0.N400 {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r PostCCIPExecuteResponse) GetJSON404() *externalRef0.N404 {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r PostCCIPExecuteResponse) GetJSON500() *externalRef0.N500 {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r PostCCIPExecuteResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostCCIPExecuteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostCCIPExecuteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostCCIPExecuteResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostCCIPSendResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *CCIPSendResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *externalRef0.N400
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *externalRef0.N404
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *externalRef0.N500
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostCCIPSendResponse) GetJSON200() *CCIPSendResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r PostCCIPSendResponse) GetJSON400() *externalRef0.N400 {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r PostCCIPSendResponse) GetJSON404() *externalRef0.N404 {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r PostCCIPSendResponse) GetJSON500() *externalRef0.N500 {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r PostCCIPSendResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostCCIPSendResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostCCIPSendResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostCCIPSendResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// PostPerPartyRouterFactoryWithBodyWithResponse performs a POST /ccip/v1/global/PerPartyRouter/factory (the `PostPerPartyRouterFactory` operationId) request,
// with any type of body and a specified content type.
//
// Get the explicit disclosures for instantiating a PerPartyRouter using the PerPartyRouterFactory.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) PostPerPartyRouterFactoryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPerPartyRouterFactoryResponse, error) {
	rsp, err := c.PostPerPartyRouterFactoryWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPerPartyRouterFactoryResponse(rsp)
}

// PostPerPartyRouterFactoryWithResponse performs a POST /ccip/v1/global/PerPartyRouter/factory (the `PostPerPartyRouterFactory` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Get the explicit disclosures for instantiating a PerPartyRouter using the PerPartyRouterFactory.
func (c *ClientWithResponses) PostPerPartyRouterFactoryWithResponse(ctx context.Context, body PostPerPartyRouterFactoryJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPerPartyRouterFactoryResponse, error) {
	rsp, err := c.PostPerPartyRouterFactory(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPerPartyRouterFactoryResponse(rsp)
}

// GetTokenAdminRegistryTokenWithResponse performs a GET /ccip/v1/global/TokenAdminRegistry/token/{instrumentId} (the `GetTokenAdminRegistryToken` operationId) request.
//
// Get the token pool for a given instrument from the token admin registry.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetTokenAdminRegistryTokenWithResponse(ctx context.Context, instrumentId externalRef0.HashedInstrumentId, reqEditors ...RequestEditorFn) (*GetTokenAdminRegistryTokenResponse, error) {
	rsp, err := c.GetTokenAdminRegistryToken(ctx, instrumentId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTokenAdminRegistryTokenResponse(rsp)
}

// PostCCIPExecuteWithBodyWithResponse performs a POST /ccip/v1/global/message/execute (the `PostCCIPExecute` operationId) request,
// with any type of body and a specified content type.
//
// Get the explicit disclosures for executing a CCIP message on Canton.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) PostCCIPExecuteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCCIPExecuteResponse, error) {
	rsp, err := c.PostCCIPExecuteWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCCIPExecuteResponse(rsp)
}

// PostCCIPExecuteWithResponse performs a POST /ccip/v1/global/message/execute (the `PostCCIPExecute` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Get the explicit disclosures for executing a CCIP message on Canton.
func (c *ClientWithResponses) PostCCIPExecuteWithResponse(ctx context.Context, body PostCCIPExecuteJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCCIPExecuteResponse, error) {
	rsp, err := c.PostCCIPExecute(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCCIPExecuteResponse(rsp)
}

// PostCCIPSendWithBodyWithResponse performs a POST /ccip/v1/global/message/send (the `PostCCIPSend` operationId) request,
// with any type of body and a specified content type.
//
// Get the explicit disclosure for sending a CCIP message from Canton.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) PostCCIPSendWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCCIPSendResponse, error) {
	rsp, err := c.PostCCIPSendWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCCIPSendResponse(rsp)
}

// PostCCIPSendWithResponse performs a POST /ccip/v1/global/message/send (the `PostCCIPSend` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Get the explicit disclosure for sending a CCIP message from Canton.
func (c *ClientWithResponses) PostCCIPSendWithResponse(ctx context.Context, body PostCCIPSendJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCCIPSendResponse, error) {
	rsp, err := c.PostCCIPSend(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCCIPSendResponse(rsp)
}

// ParsePostPerPartyRouterFactoryResponse parses an HTTP response from a PostPerPartyRouterFactoryWithResponse call
func ParsePostPerPartyRouterFactoryResponse(rsp *http.Response) (*PostPerPartyRouterFactoryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostPerPartyRouterFactoryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CCIPPerPartyRouterFactoryResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetTokenAdminRegistryTokenResponse parses an HTTP response from a GetTokenAdminRegistryTokenWithResponse call
func ParseGetTokenAdminRegistryTokenResponse(rsp *http.Response) (*GetTokenAdminRegistryTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTokenAdminRegistryTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LookupTokenPoolResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostCCIPExecuteResponse parses an HTTP response from a PostCCIPExecuteWithResponse call
func ParsePostCCIPExecuteResponse(rsp *http.Response) (*PostCCIPExecuteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostCCIPExecuteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CCIPExecuteResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostCCIPSendResponse parses an HTTP response from a PostCCIPSendWithResponse call
func ParsePostCCIPSendResponse(rsp *http.Response) (*PostCCIPSendResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostCCIPSendResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CCIPSendResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /ccip/v1/global/PerPartyRouter/factory)
	PostPerPartyRouterFactory(c *gin.Context)

	// (GET /ccip/v1/global/TokenAdminRegistry/token/{instrumentId})
	GetTokenAdminRegistryToken(c *gin.Context, instrumentId externalRef0.HashedInstrumentId)

	// (POST /ccip/v1/global/message/execute)
	PostCCIPExecute(c *gin.Context)

	// (POST /ccip/v1/global/message/send)
	PostCCIPSend(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostPerPartyRouterFactory operation middleware
func (siw *ServerInterfaceWrapper) PostPerPartyRouterFactory(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPerPartyRouterFactory(c)
}

// GetTokenAdminRegistryToken operation middleware
func (siw *ServerInterfaceWrapper) GetTokenAdminRegistryToken(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "instrumentId" -------------
	var instrumentId externalRef0.HashedInstrumentId

	err = runtime.BindStyledParameterWithOptions("simple", "instrumentId", c.Param("instrumentId"), &instrumentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter instrumentId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTokenAdminRegistryToken(c, instrumentId)
}

// PostCCIPExecute operation middleware
func (siw *ServerInterfaceWrapper) PostCCIPExecute(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostCCIPExecute(c)
}

// PostCCIPSend operation middleware
func (siw *ServerInterfaceWrapper) PostCCIPSend(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostCCIPSend(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/ccip/v1/global/PerPartyRouter/factory", wrapper.PostPerPartyRouterFactory)
	router.GET(options.BaseURL+"/ccip/v1/global/TokenAdminRegistry/token/:instrumentId", wrapper.GetTokenAdminRegistryToken)
	router.POST(options.BaseURL+"/ccip/v1/global/message/send", wrapper.PostCCIPSend)
	router.POST(options.BaseURL+"/ccip/v1/global/message/execute", wrapper.PostCCIPExecute)
}
