// Package executor provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package executor

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	externalRef0 "github.com/smartcontractkit/chainlink-canton/eds/api/common"
)

// ExecutorSendRequest defines model for ExecutorSendRequest.
type ExecutorSendRequest struct {
	Ccvs []externalRef0.RawOrHashedAddress `json:"ccvs"`

	// Message A message to be sent from Canton.
	Message externalRef0.Message `json:"message"`
}

// ExecutorSendResponse defines model for ExecutorSendResponse.
type ExecutorSendResponse struct {
	// ContextData The context to be passed along to the Executor.
	ContextData map[string]interface{} `json:"contextData"`

	// ContractId The unique identifier of a contract.
	//
	// Example: 00929f6a675c128bb54bef77a8cad8d330badd4330cf71f6a19b596b01f4b66b2dca121220cd655ce27fae64bdf6a203fcd987727de81c3762e46b1882ce2c2fbf0a72c64f
	ContractId         externalRef0.ContractId          `json:"contractId"`
	DisclosedContracts []externalRef0.DisclosedContract `json:"disclosedContracts"`

	// InstanceAddress The InstanceAddress of a contract, the keccak256 hash of the RawInstanceAddress.
	//
	// Example: 0x9d24274102a5d2f57506d48dee1394e33f7cef9a9c0920ee714d6f4a216a21a9
	InstanceAddress externalRef0.InstanceAddress `json:"instanceAddress"`

	// RawInstanceAddress The raw InstanceAddress of a contract, in the form of "prefix@owner", where prefix is the InstanceId of the contract.
	//
	// Example: some-contract-fgtlw@ccipOwner::1220131b86f50178e6f7aabe62ef79e79b4964a526a1c557776409f448cbcd2406ce
	RawInstanceAddress externalRef0.RawInstanceAddress `json:"rawInstanceAddress"`
}

// PostExecutorSendJSONRequestBody defines body for PostExecutorSend for application/json ContentType.
type PostExecutorSendJSONRequestBody = ExecutorSendRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// PostExecutorSendWithBody performs a POST /ccip/v1/external/executor/{address}/send (the `PostExecutorSend` operationId) request,
	// with any type of body and a specified content type.
	//
	// Get the explicit disclosures for sending a message using this Executor.
	PostExecutorSendWithBody(ctx context.Context, address string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostExecutorSend performs a POST /ccip/v1/external/executor/{address}/send (the `PostExecutorSend` operationId) request.
	// Takes a body of the `application/json` content type.
	//
	// Get the explicit disclosures for sending a message using this Executor.
	PostExecutorSend(ctx context.Context, address string, body PostExecutorSendJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// PostExecutorSendWithBody performs a POST /ccip/v1/external/executor/{address}/send (the `PostExecutorSend` operationId) request,
// with any type of body and a specified content type.
//
// Get the explicit disclosures for sending a message using this Executor.
func (c *Client) PostExecutorSendWithBody(ctx context.Context, address string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostExecutorSendRequestWithBody(c.Server, address, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostExecutorSend performs a POST /ccip/v1/external/executor/{address}/send (the `PostExecutorSend` operationId) request.
// Takes a body of the `application/json` content type.
//
// Get the explicit disclosures for sending a message using this Executor.
func (c *Client) PostExecutorSend(ctx context.Context, address string, body PostExecutorSendJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostExecutorSendRequest(c.Server, address, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostExecutorSendRequest calls the generic PostExecutorSend builder with application/json body
func NewPostExecutorSendRequest(server string, address string, body PostExecutorSendJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostExecutorSendRequestWithBody(server, address, "application/json", bodyReader)
}

// NewPostExecutorSendRequestWithBody constructs an http.Request for the PostExecutorSend method, with any body, and a specified content type
func NewPostExecutorSendRequestWithBody(server string, address string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "address", address, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ccip/v1/external/executor/%s/send", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// PostExecutorSendWithBodyWithResponse performs a POST /ccip/v1/external/executor/{address}/send (the `PostExecutorSend` operationId) request,
	// with any type of body and a specified content type.
	//
	// Get the explicit disclosures for sending a message using this Executor.
	//
	// Returns a wrapper object for the known response body format(s).
	PostExecutorSendWithBodyWithResponse(ctx context.Context, address string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostExecutorSendResponse, error)

	// PostExecutorSendWithResponse performs a POST /ccip/v1/external/executor/{address}/send (the `PostExecutorSend` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Get the explicit disclosures for sending a message using this Executor.
	PostExecutorSendWithResponse(ctx context.Context, address string, body PostExecutorSendJSONRequestBody, reqEditors ...RequestEditorFn) (*PostExecutorSendResponse, error)
}

type PostExecutorSendResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ExecutorSendResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *externalRef0.N400
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *externalRef0.N404
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *externalRef0.N500
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostExecutorSendResponse) GetJSON200() *ExecutorSendResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r PostExecutorSendResponse) GetJSON400() *externalRef0.N400 {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r PostExecutorSendResponse) GetJSON404() *externalRef0.N404 {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r PostExecutorSendResponse) GetJSON500() *externalRef0.N500 {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r PostExecutorSendResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostExecutorSendResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostExecutorSendResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostExecutorSendResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// PostExecutorSendWithBodyWithResponse performs a POST /ccip/v1/external/executor/{address}/send (the `PostExecutorSend` operationId) request,
// with any type of body and a specified content type.
//
// Get the explicit disclosures for sending a message using this Executor.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) PostExecutorSendWithBodyWithResponse(ctx context.Context, address string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostExecutorSendResponse, error) {
	rsp, err := c.PostExecutorSendWithBody(ctx, address, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostExecutorSendResponse(rsp)
}

// PostExecutorSendWithResponse performs a POST /ccip/v1/external/executor/{address}/send (the `PostExecutorSend` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Get the explicit disclosures for sending a message using this Executor.
func (c *ClientWithResponses) PostExecutorSendWithResponse(ctx context.Context, address string, body PostExecutorSendJSONRequestBody, reqEditors ...RequestEditorFn) (*PostExecutorSendResponse, error) {
	rsp, err := c.PostExecutorSend(ctx, address, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostExecutorSendResponse(rsp)
}

// ParsePostExecutorSendResponse parses an HTTP response from a PostExecutorSendWithResponse call
func ParsePostExecutorSendResponse(rsp *http.Response) (*PostExecutorSendResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostExecutorSendResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ExecutorSendResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /ccip/v1/external/executor/{address}/send)
	PostExecutorSend(c *gin.Context, address string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostExecutorSend operation middleware
func (siw *ServerInterfaceWrapper) PostExecutorSend(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "address" -------------
	var address string

	err = runtime.BindStyledParameterWithOptions("simple", "address", c.Param("address"), &address, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter address: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostExecutorSend(c, address)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/ccip/v1/external/executor/:address/send", wrapper.PostExecutorSend)
}
