// Package scanProxy provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package scanProxy

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for TransferCommandFailedResponseFailureKind.
const (
	Expired   TransferCommandFailedResponseFailureKind = "expired"
	Failed    TransferCommandFailedResponseFailureKind = "failed"
	Withdrawn TransferCommandFailedResponseFailureKind = "withdrawn"
)

// Valid indicates whether the value is a known member of the TransferCommandFailedResponseFailureKind enum.
func (e TransferCommandFailedResponseFailureKind) Valid() bool {
	switch e {
	case Expired:
		return true
	case Failed:
		return true
	case Withdrawn:
		return true
	default:
		return false
	}
}

// AnsEntry defines model for AnsEntry.
type AnsEntry struct {
	// ContractId If present, Daml contract ID of template `Splice.Ans:AnsEntry`.
	// If absent, this is a DSO-provided entry for either the DSO or an SV.
	ContractId *string `json:"contract_id,omitempty"`

	// Description Arbitrary description text supplied by `user`; may be empty.
	Description string `json:"description"`

	// ExpiresAt Time after which this ANS entry expires; if renewed, it will have a
	// new `contract_id` and `expires_at`.
	// If `null` or absent, does not expire; this is the case only for
	// special entries provided by the DSO.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// Name The ANS entry name.
	Name string `json:"name"`

	// Url Either empty, or an http/https URL supplied by the `user`.
	Url string `json:"url"`

	// User Owner party ID of this ANS entry.
	User string `json:"user"`
}

// BaseLookupTransferCommandStatusResponse defines model for BaseLookupTransferCommandStatusResponse.
type BaseLookupTransferCommandStatusResponse struct {
	// Status The status of the transfer command.
	// created:
	//   The transfer command has been created and is waiting for automation to complete it.
	// sent:
	//   The transfer command has been completed and the transfer to the receiver has finished.
	// failed:
	//   The transfer command has failed permanently and nothing has been transferred. Refer to
	//   failure_reason for details. A new transfer command can be created.
	Status string `json:"status"`
}

// Contract defines model for Contract.
type Contract struct {
	ContractId       string                 `json:"contract_id"`
	CreatedAt        string                 `json:"created_at"`
	CreatedEventBlob string                 `json:"created_event_blob"`
	Payload          map[string]interface{} `json:"payload"`
	TemplateId       string                 `json:"template_id"`
}

// ContractId defines model for ContractId.
type ContractId = string

// ContractWithState defines model for ContractWithState.
type ContractWithState struct {
	Contract Contract `json:"contract"`
	DomainId *string  `json:"domain_id,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// GetAmuletRulesProxyResponse defines model for GetAmuletRulesProxyResponse.
type GetAmuletRulesProxyResponse struct {
	AmuletRules ContractWithState `json:"amulet_rules"`
}

// GetAnsRulesRequest defines model for GetAnsRulesRequest.
type GetAnsRulesRequest struct {
	CachedAnsRulesContractId *ContractId `json:"cached_ans_rules_contract_id,omitempty"`
	CachedAnsRulesDomainId   *string     `json:"cached_ans_rules_domain_id,omitempty"`
}

// GetAnsRulesResponse A contract state update of Daml template `Splice.Ans.AnsRules`.
type GetAnsRulesResponse struct {
	AnsRulesUpdate MaybeCachedContractWithState `json:"ans_rules_update"`
}

// GetDsoInfoResponse defines model for GetDsoInfoResponse.
type GetDsoInfoResponse struct {
	AmuletRules ContractWithState `json:"amulet_rules"`

	// DsoPartyId Party representing the whole DSO; for Scan only, also returned by
	// `/v0/dso-party-id`
	DsoPartyId string            `json:"dso_party_id"`
	DsoRules   ContractWithState `json:"dso_rules"`

	// InitialRound Initial round from which the network bootstraps
	InitialRound      *string           `json:"initial_round,omitempty"`
	LatestMiningRound ContractWithState `json:"latest_mining_round"`

	// SvNodeStates For every one of `svs` listed in `dso_rules`, a contract of the Daml
	// template `Splice.DSO.SvState.SvNodeState`. This does not include
	// states for offboarded SVs, though they may still have an on-ledger
	// state contract
	SvNodeStates []ContractWithState `json:"sv_node_states"`

	// SvPartyId Party representing the SV
	SvPartyId string `json:"sv_party_id"`

	// SvUser User ID representing the SV
	SvUser string `json:"sv_user"`

	// VotingThreshold Threshold required to pass vote requests; also known as the
	// "governance threshold", it is always derived from the number of
	// `svs` in `dso_rules`
	VotingThreshold int `json:"voting_threshold"`
}

// GetDsoPartyIdResponse defines model for GetDsoPartyIdResponse.
type GetDsoPartyIdResponse struct {
	DsoPartyId string `json:"dso_party_id"`
}

// GetOpenAndIssuingMiningRoundsProxyResponse defines model for GetOpenAndIssuingMiningRoundsProxyResponse.
type GetOpenAndIssuingMiningRoundsProxyResponse struct {
	IssuingMiningRounds []ContractWithState `json:"issuing_mining_rounds"`
	OpenMiningRounds    []ContractWithState `json:"open_mining_rounds"`
}

// ListEntriesResponse defines model for ListEntriesResponse.
type ListEntriesResponse struct {
	Entries []AnsEntry `json:"entries"`
}

// LookupEntryByNameResponse defines model for LookupEntryByNameResponse.
type LookupEntryByNameResponse struct {
	Entry AnsEntry `json:"entry"`
}

// LookupEntryByPartyResponse defines model for LookupEntryByPartyResponse.
type LookupEntryByPartyResponse struct {
	Entry AnsEntry `json:"entry"`
}

// LookupFeaturedAppRightResponse If defined, a contract of Daml template `Splice.Amulet.FeaturedAppRight`.
type LookupFeaturedAppRightResponse struct {
	FeaturedAppRight *Contract `json:"featured_app_right,omitempty"`
}

// LookupTransferCommandCounterByPartyResponse A Daml contract of template `Splice.ExternalPartyAmuletRules:TransferCommandCounter`.
type LookupTransferCommandCounterByPartyResponse struct {
	TransferCommandCounter ContractWithState `json:"transfer_command_counter"`
}

// LookupTransferCommandStatusResponse defines model for LookupTransferCommandStatusResponse.
type LookupTransferCommandStatusResponse struct {
	TransferCommandsByContractId TransferCommandMap `json:"transfer_commands_by_contract_id"`
}

// LookupTransferPreapprovalByPartyResponse A Daml contract of template `Splice.AmuletRules:TransferPreapproval`.
type LookupTransferPreapprovalByPartyResponse struct {
	TransferPreapproval ContractWithState `json:"transfer_preapproval"`
}

// MaybeCachedContractWithState defines model for MaybeCachedContractWithState.
type MaybeCachedContractWithState struct {
	Contract *Contract `json:"contract,omitempty"`
	DomainId *string   `json:"domain_id,omitempty"`
}

// TransferCommandContractStatus defines model for TransferCommandContractStatus.
type TransferCommandContractStatus struct {
	union json.RawMessage
}

// TransferCommandContractWithStatus A contract of Daml template `Splice.ExternalPartyAmuletRules:TransferCommand`,
// and its status determined by the latest transactions.
type TransferCommandContractWithStatus struct {
	Contract Contract                      `json:"contract"`
	Status   TransferCommandContractStatus `json:"status"`
}

// TransferCommandCreatedResponse defines model for TransferCommandCreatedResponse.
type TransferCommandCreatedResponse = BaseLookupTransferCommandStatusResponse

// TransferCommandFailedResponse defines model for TransferCommandFailedResponse.
type TransferCommandFailedResponse struct {
	// FailureKind The reason for the failure of the TransferCommand.
	// failed:
	//   Completing the transfer failed, check the reason for details.
	// withdrawn:
	//   The sender has withdrawn the TransferCommand before it could be completed.
	// expired:
	//   The expiry time on the TransferCommand was reached before it could be completed.
	FailureKind TransferCommandFailedResponseFailureKind `json:"failure_kind"`

	// Reason Human readable description of the failure
	Reason string `json:"reason"`

	// Status The status of the transfer command.
	// created:
	//   The transfer command has been created and is waiting for automation to complete it.
	// sent:
	//   The transfer command has been completed and the transfer to the receiver has finished.
	// failed:
	//   The transfer command has failed permanently and nothing has been transferred. Refer to
	//   failure_reason for details. A new transfer command can be created.
	Status string `json:"status"`
}

// TransferCommandFailedResponseFailureKind The reason for the failure of the TransferCommand.
// failed:
//
//	Completing the transfer failed, check the reason for details.
//
// withdrawn:
//
//	The sender has withdrawn the TransferCommand before it could be completed.
//
// expired:
//
//	The expiry time on the TransferCommand was reached before it could be completed.
type TransferCommandFailedResponseFailureKind string

// TransferCommandMap defines model for TransferCommandMap.
type TransferCommandMap map[string]TransferCommandContractWithStatus

// TransferCommandSentResponse defines model for TransferCommandSentResponse.
type TransferCommandSentResponse = BaseLookupTransferCommandStatusResponse

// N404 defines model for 404.
type N404 = ErrorResponse

// ListAnsEntriesParams defines parameters for ListAnsEntries.
type ListAnsEntriesParams struct {
	NamePrefix *string `form:"name_prefix,omitempty" json:"name_prefix,omitempty"`
	PageSize   int32   `form:"page_size" json:"page_size"`
}

// LookupTransferCommandStatusParams defines parameters for LookupTransferCommandStatus.
type LookupTransferCommandStatusParams struct {
	Sender string `form:"sender" json:"sender"`
	Nonce  int64  `form:"nonce" json:"nonce"`
}

// GetAnsRulesJSONRequestBody defines body for GetAnsRules for application/json ContentType.
type GetAnsRulesJSONRequestBody = GetAnsRulesRequest

// AsTransferCommandCreatedResponse returns the union data inside the TransferCommandContractStatus as a TransferCommandCreatedResponse
func (t TransferCommandContractStatus) AsTransferCommandCreatedResponse() (TransferCommandCreatedResponse, error) {
	var body TransferCommandCreatedResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTransferCommandCreatedResponse overwrites any union data inside the TransferCommandContractStatus as the provided TransferCommandCreatedResponse
func (t *TransferCommandContractStatus) FromTransferCommandCreatedResponse(v TransferCommandCreatedResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"status":"created"}`))
	t.union = b
	return err
}

// MergeTransferCommandCreatedResponse performs a merge with any union data inside the TransferCommandContractStatus, using the provided TransferCommandCreatedResponse
func (t *TransferCommandContractStatus) MergeTransferCommandCreatedResponse(v TransferCommandCreatedResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"status":"created"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTransferCommandSentResponse returns the union data inside the TransferCommandContractStatus as a TransferCommandSentResponse
func (t TransferCommandContractStatus) AsTransferCommandSentResponse() (TransferCommandSentResponse, error) {
	var body TransferCommandSentResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTransferCommandSentResponse overwrites any union data inside the TransferCommandContractStatus as the provided TransferCommandSentResponse
func (t *TransferCommandContractStatus) FromTransferCommandSentResponse(v TransferCommandSentResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"status":"sent"}`))
	t.union = b
	return err
}

// MergeTransferCommandSentResponse performs a merge with any union data inside the TransferCommandContractStatus, using the provided TransferCommandSentResponse
func (t *TransferCommandContractStatus) MergeTransferCommandSentResponse(v TransferCommandSentResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"status":"sent"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTransferCommandFailedResponse returns the union data inside the TransferCommandContractStatus as a TransferCommandFailedResponse
func (t TransferCommandContractStatus) AsTransferCommandFailedResponse() (TransferCommandFailedResponse, error) {
	var body TransferCommandFailedResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTransferCommandFailedResponse overwrites any union data inside the TransferCommandContractStatus as the provided TransferCommandFailedResponse
func (t *TransferCommandContractStatus) FromTransferCommandFailedResponse(v TransferCommandFailedResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"status":"failed"}`))
	t.union = b
	return err
}

// MergeTransferCommandFailedResponse performs a merge with any union data inside the TransferCommandContractStatus, using the provided TransferCommandFailedResponse
func (t *TransferCommandContractStatus) MergeTransferCommandFailedResponse(v TransferCommandFailedResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"status":"failed"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t TransferCommandContractStatus) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"status"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t TransferCommandContractStatus) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "created":
		return t.AsTransferCommandCreatedResponse()
	case "failed":
		return t.AsTransferCommandFailedResponse()
	case "sent":
		return t.AsTransferCommandSentResponse()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t TransferCommandContractStatus) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *TransferCommandContractStatus) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetAmuletRules performs a GET /v0/scan-proxy/amulet-rules (the `GetAmuletRules` operationId) request.
	GetAmuletRules(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListAnsEntries performs a GET /v0/scan-proxy/ans-entries (the `ListAnsEntries` operationId) request.
	ListAnsEntries(ctx context.Context, params *ListAnsEntriesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LookupAnsEntryByName performs a GET /v0/scan-proxy/ans-entries/by-name/{name} (the `LookupAnsEntryByName` operationId) request.
	LookupAnsEntryByName(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LookupAnsEntryByParty performs a GET /v0/scan-proxy/ans-entries/by-party/{party} (the `LookupAnsEntryByParty` operationId) request.
	LookupAnsEntryByParty(ctx context.Context, party string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAnsRulesWithBody performs a POST /v0/scan-proxy/ans-rules (the `GetAnsRules` operationId) request,
	// with any type of body and a specified content type.
	GetAnsRulesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAnsRules performs a POST /v0/scan-proxy/ans-rules (the `GetAnsRules` operationId) request.
	// Takes a body of the `application/json` content type.
	GetAnsRules(ctx context.Context, body GetAnsRulesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDsoInfo performs a GET /v0/scan-proxy/dso (the `GetDsoInfo` operationId) request.
	GetDsoInfo(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDsoPartyId performs a GET /v0/scan-proxy/dso-party-id (the `GetDsoPartyId` operationId) request.
	GetDsoPartyId(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LookupFeaturedAppRight performs a GET /v0/scan-proxy/featured-apps/{provider_party_id} (the `LookupFeaturedAppRight` operationId) request.
	LookupFeaturedAppRight(ctx context.Context, providerPartyId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetOpenAndIssuingMiningRounds performs a GET /v0/scan-proxy/open-and-issuing-mining-rounds (the `GetOpenAndIssuingMiningRounds` operationId) request.
	GetOpenAndIssuingMiningRounds(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LookupTransferCommandCounterByParty performs a GET /v0/scan-proxy/transfer-command-counter/{party} (the `LookupTransferCommandCounterByParty` operationId) request.
	LookupTransferCommandCounterByParty(ctx context.Context, party string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LookupTransferCommandStatus performs a GET /v0/scan-proxy/transfer-command/status (the `LookupTransferCommandStatus` operationId) request.
	//
	// Retrieve the status of all transfer commands of the given sender for the specified nonce.
	LookupTransferCommandStatus(ctx context.Context, params *LookupTransferCommandStatusParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LookupTransferPreapprovalByParty performs a GET /v0/scan-proxy/transfer-preapprovals/by-party/{party} (the `LookupTransferPreapprovalByParty` operationId) request.
	LookupTransferPreapprovalByParty(ctx context.Context, party string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetAmuletRules performs a GET /v0/scan-proxy/amulet-rules (the `GetAmuletRules` operationId) request.
func (c *Client) GetAmuletRules(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAmuletRulesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListAnsEntries performs a GET /v0/scan-proxy/ans-entries (the `ListAnsEntries` operationId) request.
func (c *Client) ListAnsEntries(ctx context.Context, params *ListAnsEntriesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListAnsEntriesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// LookupAnsEntryByName performs a GET /v0/scan-proxy/ans-entries/by-name/{name} (the `LookupAnsEntryByName` operationId) request.
func (c *Client) LookupAnsEntryByName(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLookupAnsEntryByNameRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// LookupAnsEntryByParty performs a GET /v0/scan-proxy/ans-entries/by-party/{party} (the `LookupAnsEntryByParty` operationId) request.
func (c *Client) LookupAnsEntryByParty(ctx context.Context, party string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLookupAnsEntryByPartyRequest(c.Server, party)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetAnsRulesWithBody performs a POST /v0/scan-proxy/ans-rules (the `GetAnsRules` operationId) request,
// with any type of body and a specified content type.
func (c *Client) GetAnsRulesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAnsRulesRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetAnsRules performs a POST /v0/scan-proxy/ans-rules (the `GetAnsRules` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) GetAnsRules(ctx context.Context, body GetAnsRulesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAnsRulesRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetDsoInfo performs a GET /v0/scan-proxy/dso (the `GetDsoInfo` operationId) request.
func (c *Client) GetDsoInfo(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDsoInfoRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetDsoPartyId performs a GET /v0/scan-proxy/dso-party-id (the `GetDsoPartyId` operationId) request.
func (c *Client) GetDsoPartyId(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDsoPartyIdRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// LookupFeaturedAppRight performs a GET /v0/scan-proxy/featured-apps/{provider_party_id} (the `LookupFeaturedAppRight` operationId) request.
func (c *Client) LookupFeaturedAppRight(ctx context.Context, providerPartyId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLookupFeaturedAppRightRequest(c.Server, providerPartyId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetOpenAndIssuingMiningRounds performs a GET /v0/scan-proxy/open-and-issuing-mining-rounds (the `GetOpenAndIssuingMiningRounds` operationId) request.
func (c *Client) GetOpenAndIssuingMiningRounds(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOpenAndIssuingMiningRoundsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// LookupTransferCommandCounterByParty performs a GET /v0/scan-proxy/transfer-command-counter/{party} (the `LookupTransferCommandCounterByParty` operationId) request.
func (c *Client) LookupTransferCommandCounterByParty(ctx context.Context, party string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLookupTransferCommandCounterByPartyRequest(c.Server, party)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// LookupTransferCommandStatus performs a GET /v0/scan-proxy/transfer-command/status (the `LookupTransferCommandStatus` operationId) request.
//
// Retrieve the status of all transfer commands of the given sender for the specified nonce.
func (c *Client) LookupTransferCommandStatus(ctx context.Context, params *LookupTransferCommandStatusParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLookupTransferCommandStatusRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// LookupTransferPreapprovalByParty performs a GET /v0/scan-proxy/transfer-preapprovals/by-party/{party} (the `LookupTransferPreapprovalByParty` operationId) request.
func (c *Client) LookupTransferPreapprovalByParty(ctx context.Context, party string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLookupTransferPreapprovalByPartyRequest(c.Server, party)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAmuletRulesRequest constructs an http.Request for the GetAmuletRules method
func NewGetAmuletRulesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v0/scan-proxy/amulet-rules")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListAnsEntriesRequest constructs an http.Request for the ListAnsEntries method
func NewListAnsEntriesRequest(server string, params *ListAnsEntriesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v0/scan-proxy/ans-entries")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.NamePrefix != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "name_prefix", *params.NamePrefix, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page_size", params.PageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewLookupAnsEntryByNameRequest constructs an http.Request for the LookupAnsEntryByName method
func NewLookupAnsEntryByNameRequest(server string, name string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v0/scan-proxy/ans-entries/by-name/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewLookupAnsEntryByPartyRequest constructs an http.Request for the LookupAnsEntryByParty method
func NewLookupAnsEntryByPartyRequest(server string, party string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "party", party, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v0/scan-proxy/ans-entries/by-party/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAnsRulesRequest calls the generic GetAnsRules builder with application/json body
func NewGetAnsRulesRequest(server string, body GetAnsRulesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGetAnsRulesRequestWithBody(server, "application/json", bodyReader)
}

// NewGetAnsRulesRequestWithBody constructs an http.Request for the GetAnsRules method, with any body, and a specified content type
func NewGetAnsRulesRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v0/scan-proxy/ans-rules")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetDsoInfoRequest constructs an http.Request for the GetDsoInfo method
func NewGetDsoInfoRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v0/scan-proxy/dso")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDsoPartyIdRequest constructs an http.Request for the GetDsoPartyId method
func NewGetDsoPartyIdRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v0/scan-proxy/dso-party-id")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewLookupFeaturedAppRightRequest constructs an http.Request for the LookupFeaturedAppRight method
func NewLookupFeaturedAppRightRequest(server string, providerPartyId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "provider_party_id", providerPartyId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v0/scan-proxy/featured-apps/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetOpenAndIssuingMiningRoundsRequest constructs an http.Request for the GetOpenAndIssuingMiningRounds method
func NewGetOpenAndIssuingMiningRoundsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v0/scan-proxy/open-and-issuing-mining-rounds")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewLookupTransferCommandCounterByPartyRequest constructs an http.Request for the LookupTransferCommandCounterByParty method
func NewLookupTransferCommandCounterByPartyRequest(server string, party string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "party", party, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v0/scan-proxy/transfer-command-counter/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewLookupTransferCommandStatusRequest constructs an http.Request for the LookupTransferCommandStatus method
func NewLookupTransferCommandStatusRequest(server string, params *LookupTransferCommandStatusParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v0/scan-proxy/transfer-command/status")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sender", params.Sender, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "nonce", params.Nonce, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewLookupTransferPreapprovalByPartyRequest constructs an http.Request for the LookupTransferPreapprovalByParty method
func NewLookupTransferPreapprovalByPartyRequest(server string, party string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "party", party, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v0/scan-proxy/transfer-preapprovals/by-party/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetAmuletRulesWithResponse performs a GET /v0/scan-proxy/amulet-rules (the `GetAmuletRules` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	GetAmuletRulesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAmuletRulesResp, error)

	// ListAnsEntriesWithResponse performs a GET /v0/scan-proxy/ans-entries (the `ListAnsEntries` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	ListAnsEntriesWithResponse(ctx context.Context, params *ListAnsEntriesParams, reqEditors ...RequestEditorFn) (*ListAnsEntriesResp, error)

	// LookupAnsEntryByNameWithResponse performs a GET /v0/scan-proxy/ans-entries/by-name/{name} (the `LookupAnsEntryByName` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	LookupAnsEntryByNameWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*LookupAnsEntryByNameResp, error)

	// LookupAnsEntryByPartyWithResponse performs a GET /v0/scan-proxy/ans-entries/by-party/{party} (the `LookupAnsEntryByParty` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	LookupAnsEntryByPartyWithResponse(ctx context.Context, party string, reqEditors ...RequestEditorFn) (*LookupAnsEntryByPartyResp, error)

	// GetAnsRulesWithBodyWithResponse performs a POST /v0/scan-proxy/ans-rules (the `GetAnsRules` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	GetAnsRulesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetAnsRulesResp, error)

	// GetAnsRulesWithResponse performs a POST /v0/scan-proxy/ans-rules (the `GetAnsRules` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	GetAnsRulesWithResponse(ctx context.Context, body GetAnsRulesJSONRequestBody, reqEditors ...RequestEditorFn) (*GetAnsRulesResp, error)

	// GetDsoInfoWithResponse performs a GET /v0/scan-proxy/dso (the `GetDsoInfo` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	GetDsoInfoWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetDsoInfoResp, error)

	// GetDsoPartyIdWithResponse performs a GET /v0/scan-proxy/dso-party-id (the `GetDsoPartyId` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	GetDsoPartyIdWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetDsoPartyIdResp, error)

	// LookupFeaturedAppRightWithResponse performs a GET /v0/scan-proxy/featured-apps/{provider_party_id} (the `LookupFeaturedAppRight` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	LookupFeaturedAppRightWithResponse(ctx context.Context, providerPartyId string, reqEditors ...RequestEditorFn) (*LookupFeaturedAppRightResp, error)

	// GetOpenAndIssuingMiningRoundsWithResponse performs a GET /v0/scan-proxy/open-and-issuing-mining-rounds (the `GetOpenAndIssuingMiningRounds` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	GetOpenAndIssuingMiningRoundsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetOpenAndIssuingMiningRoundsResp, error)

	// LookupTransferCommandCounterByPartyWithResponse performs a GET /v0/scan-proxy/transfer-command-counter/{party} (the `LookupTransferCommandCounterByParty` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	LookupTransferCommandCounterByPartyWithResponse(ctx context.Context, party string, reqEditors ...RequestEditorFn) (*LookupTransferCommandCounterByPartyResp, error)

	// LookupTransferCommandStatusWithResponse performs a GET /v0/scan-proxy/transfer-command/status (the `LookupTransferCommandStatus` operationId) request.
	//
	// Retrieve the status of all transfer commands of the given sender for the specified nonce.
	//
	// Returns a wrapper object for the known response body format(s).
	LookupTransferCommandStatusWithResponse(ctx context.Context, params *LookupTransferCommandStatusParams, reqEditors ...RequestEditorFn) (*LookupTransferCommandStatusResp, error)

	// LookupTransferPreapprovalByPartyWithResponse performs a GET /v0/scan-proxy/transfer-preapprovals/by-party/{party} (the `LookupTransferPreapprovalByParty` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	LookupTransferPreapprovalByPartyWithResponse(ctx context.Context, party string, reqEditors ...RequestEditorFn) (*LookupTransferPreapprovalByPartyResp, error)
}

type GetAmuletRulesResp struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *GetAmuletRulesProxyResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetAmuletRulesResp) GetJSON200() *GetAmuletRulesProxyResponse {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetAmuletRulesResp) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetAmuletRulesResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAmuletRulesResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAmuletRulesResp) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListAnsEntriesResp struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ListEntriesResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListAnsEntriesResp) GetJSON200() *ListEntriesResponse {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r ListAnsEntriesResp) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListAnsEntriesResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListAnsEntriesResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListAnsEntriesResp) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type LookupAnsEntryByNameResp struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *LookupEntryByNameResponse
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *N404
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r LookupAnsEntryByNameResp) GetJSON200() *LookupEntryByNameResponse {
	return r.JSON200
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r LookupAnsEntryByNameResp) GetJSON404() *N404 {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r LookupAnsEntryByNameResp) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r LookupAnsEntryByNameResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LookupAnsEntryByNameResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r LookupAnsEntryByNameResp) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type LookupAnsEntryByPartyResp struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *LookupEntryByPartyResponse
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *N404
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r LookupAnsEntryByPartyResp) GetJSON200() *LookupEntryByPartyResponse {
	return r.JSON200
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r LookupAnsEntryByPartyResp) GetJSON404() *N404 {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r LookupAnsEntryByPartyResp) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r LookupAnsEntryByPartyResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LookupAnsEntryByPartyResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r LookupAnsEntryByPartyResp) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAnsRulesResp struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *GetAnsRulesResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetAnsRulesResp) GetJSON200() *GetAnsRulesResponse {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetAnsRulesResp) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetAnsRulesResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAnsRulesResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAnsRulesResp) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetDsoInfoResp struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *GetDsoInfoResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetDsoInfoResp) GetJSON200() *GetDsoInfoResponse {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetDsoInfoResp) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetDsoInfoResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDsoInfoResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetDsoInfoResp) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetDsoPartyIdResp struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *GetDsoPartyIdResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetDsoPartyIdResp) GetJSON200() *GetDsoPartyIdResponse {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetDsoPartyIdResp) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetDsoPartyIdResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDsoPartyIdResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetDsoPartyIdResp) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type LookupFeaturedAppRightResp struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *LookupFeaturedAppRightResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r LookupFeaturedAppRightResp) GetJSON200() *LookupFeaturedAppRightResponse {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r LookupFeaturedAppRightResp) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r LookupFeaturedAppRightResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LookupFeaturedAppRightResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r LookupFeaturedAppRightResp) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetOpenAndIssuingMiningRoundsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *GetOpenAndIssuingMiningRoundsProxyResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetOpenAndIssuingMiningRoundsResp) GetJSON200() *GetOpenAndIssuingMiningRoundsProxyResponse {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetOpenAndIssuingMiningRoundsResp) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetOpenAndIssuingMiningRoundsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOpenAndIssuingMiningRoundsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetOpenAndIssuingMiningRoundsResp) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type LookupTransferCommandCounterByPartyResp struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *LookupTransferCommandCounterByPartyResponse
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *N404
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r LookupTransferCommandCounterByPartyResp) GetJSON200() *LookupTransferCommandCounterByPartyResponse {
	return r.JSON200
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r LookupTransferCommandCounterByPartyResp) GetJSON404() *N404 {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r LookupTransferCommandCounterByPartyResp) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r LookupTransferCommandCounterByPartyResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LookupTransferCommandCounterByPartyResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r LookupTransferCommandCounterByPartyResp) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type LookupTransferCommandStatusResp struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *LookupTransferCommandStatusResponse
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *N404
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r LookupTransferCommandStatusResp) GetJSON200() *LookupTransferCommandStatusResponse {
	return r.JSON200
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r LookupTransferCommandStatusResp) GetJSON404() *N404 {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r LookupTransferCommandStatusResp) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r LookupTransferCommandStatusResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LookupTransferCommandStatusResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r LookupTransferCommandStatusResp) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type LookupTransferPreapprovalByPartyResp struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *LookupTransferPreapprovalByPartyResponse
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *N404
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r LookupTransferPreapprovalByPartyResp) GetJSON200() *LookupTransferPreapprovalByPartyResponse {
	return r.JSON200
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r LookupTransferPreapprovalByPartyResp) GetJSON404() *N404 {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r LookupTransferPreapprovalByPartyResp) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r LookupTransferPreapprovalByPartyResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LookupTransferPreapprovalByPartyResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r LookupTransferPreapprovalByPartyResp) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetAmuletRulesWithResponse performs a GET /v0/scan-proxy/amulet-rules (the `GetAmuletRules` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetAmuletRulesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAmuletRulesResp, error) {
	rsp, err := c.GetAmuletRules(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAmuletRulesResp(rsp)
}

// ListAnsEntriesWithResponse performs a GET /v0/scan-proxy/ans-entries (the `ListAnsEntries` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) ListAnsEntriesWithResponse(ctx context.Context, params *ListAnsEntriesParams, reqEditors ...RequestEditorFn) (*ListAnsEntriesResp, error) {
	rsp, err := c.ListAnsEntries(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListAnsEntriesResp(rsp)
}

// LookupAnsEntryByNameWithResponse performs a GET /v0/scan-proxy/ans-entries/by-name/{name} (the `LookupAnsEntryByName` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) LookupAnsEntryByNameWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*LookupAnsEntryByNameResp, error) {
	rsp, err := c.LookupAnsEntryByName(ctx, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLookupAnsEntryByNameResp(rsp)
}

// LookupAnsEntryByPartyWithResponse performs a GET /v0/scan-proxy/ans-entries/by-party/{party} (the `LookupAnsEntryByParty` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) LookupAnsEntryByPartyWithResponse(ctx context.Context, party string, reqEditors ...RequestEditorFn) (*LookupAnsEntryByPartyResp, error) {
	rsp, err := c.LookupAnsEntryByParty(ctx, party, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLookupAnsEntryByPartyResp(rsp)
}

// GetAnsRulesWithBodyWithResponse performs a POST /v0/scan-proxy/ans-rules (the `GetAnsRules` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetAnsRulesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetAnsRulesResp, error) {
	rsp, err := c.GetAnsRulesWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAnsRulesResp(rsp)
}

// GetAnsRulesWithResponse performs a POST /v0/scan-proxy/ans-rules (the `GetAnsRules` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetAnsRulesWithResponse(ctx context.Context, body GetAnsRulesJSONRequestBody, reqEditors ...RequestEditorFn) (*GetAnsRulesResp, error) {
	rsp, err := c.GetAnsRules(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAnsRulesResp(rsp)
}

// GetDsoInfoWithResponse performs a GET /v0/scan-proxy/dso (the `GetDsoInfo` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetDsoInfoWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetDsoInfoResp, error) {
	rsp, err := c.GetDsoInfo(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDsoInfoResp(rsp)
}

// GetDsoPartyIdWithResponse performs a GET /v0/scan-proxy/dso-party-id (the `GetDsoPartyId` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetDsoPartyIdWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetDsoPartyIdResp, error) {
	rsp, err := c.GetDsoPartyId(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDsoPartyIdResp(rsp)
}

// LookupFeaturedAppRightWithResponse performs a GET /v0/scan-proxy/featured-apps/{provider_party_id} (the `LookupFeaturedAppRight` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) LookupFeaturedAppRightWithResponse(ctx context.Context, providerPartyId string, reqEditors ...RequestEditorFn) (*LookupFeaturedAppRightResp, error) {
	rsp, err := c.LookupFeaturedAppRight(ctx, providerPartyId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLookupFeaturedAppRightResp(rsp)
}

// GetOpenAndIssuingMiningRoundsWithResponse performs a GET /v0/scan-proxy/open-and-issuing-mining-rounds (the `GetOpenAndIssuingMiningRounds` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetOpenAndIssuingMiningRoundsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetOpenAndIssuingMiningRoundsResp, error) {
	rsp, err := c.GetOpenAndIssuingMiningRounds(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOpenAndIssuingMiningRoundsResp(rsp)
}

// LookupTransferCommandCounterByPartyWithResponse performs a GET /v0/scan-proxy/transfer-command-counter/{party} (the `LookupTransferCommandCounterByParty` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) LookupTransferCommandCounterByPartyWithResponse(ctx context.Context, party string, reqEditors ...RequestEditorFn) (*LookupTransferCommandCounterByPartyResp, error) {
	rsp, err := c.LookupTransferCommandCounterByParty(ctx, party, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLookupTransferCommandCounterByPartyResp(rsp)
}

// LookupTransferCommandStatusWithResponse performs a GET /v0/scan-proxy/transfer-command/status (the `LookupTransferCommandStatus` operationId) request.
//
// Retrieve the status of all transfer commands of the given sender for the specified nonce.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) LookupTransferCommandStatusWithResponse(ctx context.Context, params *LookupTransferCommandStatusParams, reqEditors ...RequestEditorFn) (*LookupTransferCommandStatusResp, error) {
	rsp, err := c.LookupTransferCommandStatus(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLookupTransferCommandStatusResp(rsp)
}

// LookupTransferPreapprovalByPartyWithResponse performs a GET /v0/scan-proxy/transfer-preapprovals/by-party/{party} (the `LookupTransferPreapprovalByParty` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) LookupTransferPreapprovalByPartyWithResponse(ctx context.Context, party string, reqEditors ...RequestEditorFn) (*LookupTransferPreapprovalByPartyResp, error) {
	rsp, err := c.LookupTransferPreapprovalByParty(ctx, party, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLookupTransferPreapprovalByPartyResp(rsp)
}

// ParseGetAmuletRulesResp parses an HTTP response from a GetAmuletRulesWithResponse call
func ParseGetAmuletRulesResp(rsp *http.Response) (*GetAmuletRulesResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAmuletRulesResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetAmuletRulesProxyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListAnsEntriesResp parses an HTTP response from a ListAnsEntriesWithResponse call
func ParseListAnsEntriesResp(rsp *http.Response) (*ListAnsEntriesResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListAnsEntriesResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListEntriesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseLookupAnsEntryByNameResp parses an HTTP response from a LookupAnsEntryByNameWithResponse call
func ParseLookupAnsEntryByNameResp(rsp *http.Response) (*LookupAnsEntryByNameResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LookupAnsEntryByNameResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LookupEntryByNameResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseLookupAnsEntryByPartyResp parses an HTTP response from a LookupAnsEntryByPartyWithResponse call
func ParseLookupAnsEntryByPartyResp(rsp *http.Response) (*LookupAnsEntryByPartyResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LookupAnsEntryByPartyResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LookupEntryByPartyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetAnsRulesResp parses an HTTP response from a GetAnsRulesWithResponse call
func ParseGetAnsRulesResp(rsp *http.Response) (*GetAnsRulesResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAnsRulesResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetAnsRulesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetDsoInfoResp parses an HTTP response from a GetDsoInfoWithResponse call
func ParseGetDsoInfoResp(rsp *http.Response) (*GetDsoInfoResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDsoInfoResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetDsoInfoResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetDsoPartyIdResp parses an HTTP response from a GetDsoPartyIdWithResponse call
func ParseGetDsoPartyIdResp(rsp *http.Response) (*GetDsoPartyIdResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDsoPartyIdResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetDsoPartyIdResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseLookupFeaturedAppRightResp parses an HTTP response from a LookupFeaturedAppRightWithResponse call
func ParseLookupFeaturedAppRightResp(rsp *http.Response) (*LookupFeaturedAppRightResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LookupFeaturedAppRightResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LookupFeaturedAppRightResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetOpenAndIssuingMiningRoundsResp parses an HTTP response from a GetOpenAndIssuingMiningRoundsWithResponse call
func ParseGetOpenAndIssuingMiningRoundsResp(rsp *http.Response) (*GetOpenAndIssuingMiningRoundsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOpenAndIssuingMiningRoundsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetOpenAndIssuingMiningRoundsProxyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseLookupTransferCommandCounterByPartyResp parses an HTTP response from a LookupTransferCommandCounterByPartyWithResponse call
func ParseLookupTransferCommandCounterByPartyResp(rsp *http.Response) (*LookupTransferCommandCounterByPartyResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LookupTransferCommandCounterByPartyResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LookupTransferCommandCounterByPartyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseLookupTransferCommandStatusResp parses an HTTP response from a LookupTransferCommandStatusWithResponse call
func ParseLookupTransferCommandStatusResp(rsp *http.Response) (*LookupTransferCommandStatusResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LookupTransferCommandStatusResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LookupTransferCommandStatusResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseLookupTransferPreapprovalByPartyResp parses an HTTP response from a LookupTransferPreapprovalByPartyWithResponse call
func ParseLookupTransferPreapprovalByPartyResp(rsp *http.Response) (*LookupTransferPreapprovalByPartyResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LookupTransferPreapprovalByPartyResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LookupTransferPreapprovalByPartyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /v0/scan-proxy/amulet-rules)
	GetAmuletRules(c *gin.Context)

	// (GET /v0/scan-proxy/ans-entries)
	ListAnsEntries(c *gin.Context, params ListAnsEntriesParams)

	// (GET /v0/scan-proxy/ans-entries/by-name/{name})
	LookupAnsEntryByName(c *gin.Context, name string)

	// (GET /v0/scan-proxy/ans-entries/by-party/{party})
	LookupAnsEntryByParty(c *gin.Context, party string)

	// (POST /v0/scan-proxy/ans-rules)
	GetAnsRules(c *gin.Context)

	// (GET /v0/scan-proxy/dso)
	GetDsoInfo(c *gin.Context)

	// (GET /v0/scan-proxy/dso-party-id)
	GetDsoPartyId(c *gin.Context)

	// (GET /v0/scan-proxy/featured-apps/{provider_party_id})
	LookupFeaturedAppRight(c *gin.Context, providerPartyId string)

	// (GET /v0/scan-proxy/open-and-issuing-mining-rounds)
	GetOpenAndIssuingMiningRounds(c *gin.Context)

	// (GET /v0/scan-proxy/transfer-command-counter/{party})
	LookupTransferCommandCounterByParty(c *gin.Context, party string)

	// (GET /v0/scan-proxy/transfer-command/status)
	LookupTransferCommandStatus(c *gin.Context, params LookupTransferCommandStatusParams)

	// (GET /v0/scan-proxy/transfer-preapprovals/by-party/{party})
	LookupTransferPreapprovalByParty(c *gin.Context, party string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAmuletRules operation middleware
func (siw *ServerInterfaceWrapper) GetAmuletRules(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAmuletRules(c)
}

// ListAnsEntries operation middleware
func (siw *ServerInterfaceWrapper) ListAnsEntries(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAnsEntriesParams

	// ------------- Optional query parameter "name_prefix" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "name_prefix", c.Request.URL.Query(), &params.NamePrefix, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name_prefix: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "page_size", c.Request.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page_size: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAnsEntries(c, params)
}

// LookupAnsEntryByName operation middleware
func (siw *ServerInterfaceWrapper) LookupAnsEntryByName(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LookupAnsEntryByName(c, name)
}

// LookupAnsEntryByParty operation middleware
func (siw *ServerInterfaceWrapper) LookupAnsEntryByParty(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "party" -------------
	var party string

	err = runtime.BindStyledParameterWithOptions("simple", "party", c.Param("party"), &party, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter party: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LookupAnsEntryByParty(c, party)
}

// GetAnsRules operation middleware
func (siw *ServerInterfaceWrapper) GetAnsRules(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAnsRules(c)
}

// GetDsoInfo operation middleware
func (siw *ServerInterfaceWrapper) GetDsoInfo(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDsoInfo(c)
}

// GetDsoPartyId operation middleware
func (siw *ServerInterfaceWrapper) GetDsoPartyId(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDsoPartyId(c)
}

// LookupFeaturedAppRight operation middleware
func (siw *ServerInterfaceWrapper) LookupFeaturedAppRight(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "provider_party_id" -------------
	var providerPartyId string

	err = runtime.BindStyledParameterWithOptions("simple", "provider_party_id", c.Param("provider_party_id"), &providerPartyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter provider_party_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LookupFeaturedAppRight(c, providerPartyId)
}

// GetOpenAndIssuingMiningRounds operation middleware
func (siw *ServerInterfaceWrapper) GetOpenAndIssuingMiningRounds(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOpenAndIssuingMiningRounds(c)
}

// LookupTransferCommandCounterByParty operation middleware
func (siw *ServerInterfaceWrapper) LookupTransferCommandCounterByParty(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "party" -------------
	var party string

	err = runtime.BindStyledParameterWithOptions("simple", "party", c.Param("party"), &party, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter party: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LookupTransferCommandCounterByParty(c, party)
}

// LookupTransferCommandStatus operation middleware
func (siw *ServerInterfaceWrapper) LookupTransferCommandStatus(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params LookupTransferCommandStatusParams

	// ------------- Required query parameter "sender" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "sender", c.Request.URL.Query(), &params.Sender, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sender: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "nonce" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "nonce", c.Request.URL.Query(), &params.Nonce, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter nonce: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LookupTransferCommandStatus(c, params)
}

// LookupTransferPreapprovalByParty operation middleware
func (siw *ServerInterfaceWrapper) LookupTransferPreapprovalByParty(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "party" -------------
	var party string

	err = runtime.BindStyledParameterWithOptions("simple", "party", c.Param("party"), &party, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter party: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LookupTransferPreapprovalByParty(c, party)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/v0/scan-proxy/dso-party-id", wrapper.GetDsoPartyId)
	router.GET(options.BaseURL+"/v0/scan-proxy/dso", wrapper.GetDsoInfo)
	router.GET(options.BaseURL+"/v0/scan-proxy/featured-apps/:provider_party_id", wrapper.LookupFeaturedAppRight)
	router.GET(options.BaseURL+"/v0/scan-proxy/open-and-issuing-mining-rounds", wrapper.GetOpenAndIssuingMiningRounds)
	router.GET(options.BaseURL+"/v0/scan-proxy/amulet-rules", wrapper.GetAmuletRules)
	router.GET(options.BaseURL+"/v0/scan-proxy/ans-entries/by-party/:party", wrapper.LookupAnsEntryByParty)
	router.GET(options.BaseURL+"/v0/scan-proxy/ans-entries", wrapper.ListAnsEntries)
	router.GET(options.BaseURL+"/v0/scan-proxy/ans-entries/by-name/:name", wrapper.LookupAnsEntryByName)
	router.POST(options.BaseURL+"/v0/scan-proxy/ans-rules", wrapper.GetAnsRules)
	router.GET(options.BaseURL+"/v0/scan-proxy/transfer-preapprovals/by-party/:party", wrapper.LookupTransferPreapprovalByParty)
	router.GET(options.BaseURL+"/v0/scan-proxy/transfer-command-counter/:party", wrapper.LookupTransferCommandCounterByParty)
	router.GET(options.BaseURL+"/v0/scan-proxy/transfer-command/status", wrapper.LookupTransferCommandStatus)
}
