# Use this configuration file to run integration tests against a locally running Docker Compose environment.
# See /compose/localnet to set up the environment.

selector=8706591216959472610

scan_api_url="http://scan.localhost:8080"
registry_api_url="http://scan.localhost:8080"

[[participants]]
name="Participant 1"
jwt="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsZWRnZXItYXBpLXVzZXIiLCJhdWQiOlsiaHR0cHM6Ly9jYW50b24ubmV0d29yay5nbG9iYWwiXSwiZXhwIjoyMDg0Nzg5NTkyLCJuYmYiOjE3Njk0Mjk1OTIsImlhdCI6MTc2OTQyOTU5Mn0.Ko98O1CvVKnwIdrYWgnVn7ooeRcmJrD5HaXG6sZjbJ0" # long running JWT, valid for 10 years+
username="ledger-api-user"
json_ledger_api_url="http://participant1.json-ledger-api.localhost:8080"
grpc_ledger_api_url="participant1.grpc-ledger-api.localhost:8080"
admin_api_url="participant1.admin-api.localhost:8080"
validator_api_url="http://participant1.validator-api.localhost:8080/api/validator"

[[participants]]
name="Participant 2"
jwt="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsZWRnZXItYXBpLXVzZXIiLCJhdWQiOlsiaHR0cHM6Ly9jYW50b24ubmV0d29yay5nbG9iYWwiXSwiZXhwIjoyMDg0Nzg5NTkyLCJuYmYiOjE3Njk0Mjk1OTIsImlhdCI6MTc2OTQyOTU5Mn0.Ko98O1CvVKnwIdrYWgnVn7ooeRcmJrD5HaXG6sZjbJ0"
username="ledger-api-user"
json_ledger_api_url="http://participant2.json-ledger-api.localhost:8080"
grpc_ledger_api_url="participant2.grpc-ledger-api.localhost:8080"
admin_api_url="participant2.admin-api.localhost:8080"
validator_api_url="http://participant2.validator-api.localhost:8080/api/validator"

[[participants]]
name="Participant 3"
jwt="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsZWRnZXItYXBpLXVzZXIiLCJhdWQiOlsiaHR0cHM6Ly9jYW50b24ubmV0d29yay5nbG9iYWwiXSwiZXhwIjoyMDg0Nzg5NTkyLCJuYmYiOjE3Njk0Mjk1OTIsImlhdCI6MTc2OTQyOTU5Mn0.Ko98O1CvVKnwIdrYWgnVn7ooeRcmJrD5HaXG6sZjbJ0"
username="ledger-api-user"
json_ledger_api_url="http://participant3.json-ledger-api.localhost:8080"
grpc_ledger_api_url="participant3.grpc-ledger-api.localhost:8080"
admin_api_url="participant3.admin-api.localhost:8080"
validator_api_url="http://participant3.validator-api.localhost:8080/api/validator"

[[participants]]
name="Participant 4"
jwt="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsZWRnZXItYXBpLXVzZXIiLCJhdWQiOlsiaHR0cHM6Ly9jYW50b24ubmV0d29yay5nbG9iYWwiXSwiZXhwIjoyMDg0Nzg5NTkyLCJuYmYiOjE3Njk0Mjk1OTIsImlhdCI6MTc2OTQyOTU5Mn0.Ko98O1CvVKnwIdrYWgnVn7ooeRcmJrD5HaXG6sZjbJ0"
username="ledger-api-user"
json_ledger_api_url="http://participant4.json-ledger-api.localhost:8080"
grpc_ledger_api_url="participant4.grpc-ledger-api.localhost:8080"
admin_api_url="participant4.admin-api.localhost:8080"
validator_api_url="http://participant4.validator-api.localhost:8080/api/validator"

[[participants]]
name="Participant 5"
jwt="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsZWRnZXItYXBpLXVzZXIiLCJhdWQiOlsiaHR0cHM6Ly9jYW50b24ubmV0d29yay5nbG9iYWwiXSwiZXhwIjoyMDg0Nzg5NTkyLCJuYmYiOjE3Njk0Mjk1OTIsImlhdCI6MTc2OTQyOTU5Mn0.Ko98O1CvVKnwIdrYWgnVn7ooeRcmJrD5HaXG6sZjbJ0"
username="ledger-api-user"
json_ledger_api_url="http://participant5.json-ledger-api.localhost:8080"
grpc_ledger_api_url="participant5.grpc-ledger-api.localhost:8080"
admin_api_url="participant5.admin-api.localhost:8080"
validator_api_url="http://participant5.validator-api.localhost:8080/api/validator"
