name: CCIP Tests
on:
  push:
    branches: [develop, main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-ccip:
    name: CCIP unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Run CCIP tests
        run: go test -short -v -count 1 ./ccip/...
      - name: Run commonconfig tests
        run: go test -short -v -count 1 ./commonconfig/...
