name: Changeset Tests
on:
  push:
    branches: [develop, main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-deploy-chain-contracts:
    name: TestDeployChainContracts
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Run Go tests
        run: |
          cd deployment/changesets
          go test -v -count 1 -timeout 20m -run TestDeployChainContracts ./...
  test-deploy-coin:
    name: TestDeployCoin
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Run Go tests
        run: |
          cd deployment/changesets
          go test -v -count 1 -timeout 20m -run TestDeployCoin ./...
  test-deploy-tps:
    name: TestDeployTokenPool
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Run Go tests
        run: |
          cd deployment/changesets
          go test -v -count 1 -timeout 20m -run TestDeployTokenPool ./...
