name: Committee Verifier Docker Build
on:
  push:
    branches: [develop, main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build committee verifier image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build image
        run: docker build -t committeeverifier-canton -f ccip/committee_verifier.Dockerfile .
