name: Daml Contracts
on:
  push:
    branches: [develop, main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Daml Contracts
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install DPM
        uses: ./.github/actions/install-dpm
      - name: Test Daml Contracts
        run: make test-daml-contracts
