name: MCMS Integration Tests
on:
  push:
    branches: [develop, main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-mcms:
    name: TestMCMS_Execute
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: integration-tests/go.mod
          cache-dependency-path: integration-tests/go.sum
      - name: Run Go tests
        run: |
          cd integration-tests/mcms
          go test -v -count 1 -timeout 20m -run TestMCMS_Execute ./...

  test-ccip-factory-mcms:
    name: TestCCIP_MCMSFactoryDeploy_FullGovernance
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: integration-tests/go.mod
          cache-dependency-path: integration-tests/go.sum
      - name: Run Go tests
        run: |
          cd integration-tests/mcms
          go test -v -count 1 -timeout 20m -run TestCCIP_MCMSFactoryDeploy_FullGovernance ./...

  test-mcms-timelock:
    name: TestMCMS_Timelock
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: integration-tests/go.mod
          cache-dependency-path: integration-tests/go.sum
      - name: Run Go tests
        run: |
          cd integration-tests/mcms
          go test -v -count 1 -timeout 20m -run TestMCMS_Timelock ./...

  test-mcms-changeset-proposal:
    name: TestMCMS_ChangesetProposalE2E
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: integration-tests/go.mod
          cache-dependency-path: integration-tests/go.sum
      - name: Run Go tests
        run: |
          cd integration-tests/mcms
          go test -v -count 1 -timeout 20m -run TestMCMS_ChangesetProposalE2E ./...
