name: Party Ceremony Integration Tests
on:
  push:
    branches: [ develop, main ]
  pull_request:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-ceremonies:
    name: Test Ceremonies
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: party-ceremony/integration-tests/go.mod
          cache-dependency-path: party-ceremony/integration-tests/go.sum
      - name: Run Go tests
        run: |
          cd party-ceremony
          make test-integration
