name: Autofix PR
on:
  pull_request:
    types:
      - labeled
      - synchronize
  repository_dispatch:
    types: [ auto-fix-command ] # ChatOps dispatch

permissions: {}
jobs:
  fix-pr:
    name: Fix PR
    if: ${{ contains(github.event.pull_request.labels.*.name, 'autofix') || github.event.client_payload.slash_command.comman == 'repository_dispatch' }}
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Install DPM
        uses: ./.github/actions/install-dpm
        # Run Fixes
      - name: Run fixes
        run: make fix-all
      - name: Create commit
        id: commit
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            git config --global user.name "Login will be determined by the Github API based on the creator of the token"
            git config --global user.email ""
            git commit -am "[autofix] apply fix-all to PR"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
      - name: Setup GitHub Token
        if: steps.commit.outputs.has_changes == 'true'
        id: setup-github-token
        uses: smartcontractkit/.github/actions/setup-github-token@ef78fa97bf3c77de6563db1175422703e9e6674f # setup-github-token@0.2.1
        with:
          aws-role-arn: ${{ secrets.GATI_AWS_ROLE_CANTON_CICD }}
          aws-lambda-url: ${{ secrets.GATI_AWS_LABDA_URL_INTEGRATIONS }}
          aws-region: ${{ secrets.GATI_AWS_REGION }}
      - name: Push signed commits
        if: steps.commit.outputs.has_changes == 'true'
        uses: asana/push-signed-commits@d615ca88d8e1a946734c24970d1e7a6c56f34897 # v1
        with:
          github-token: ${{ steps.setup-github-token.outputs.access-token }}
          local_branch_name: ${{ github.head_ref }}
          remote_name: "origin"
          remote_branch_name: ${{ github.head_ref }}