name: Autofix PR
on:
  repository_dispatch:
    types: [ auto-fix-command ] # ChatOps dispatch

env:
  GOLANGCI_LINT_VERSION: v2.8.0

permissions: {}
jobs:
  fix-pr:
    name: Fix PR
    if: github.event.client_payload.slash_command.command == 'auto-fix'
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup GitHub Token
        id: setup-github-token
        uses: smartcontractkit/.github/actions/setup-github-token@ef78fa97bf3c77de6563db1175422703e9e6674f # setup-github-token@0.2.1
        with:
          aws-role-arn: ${{ secrets.GATI_AWS_ROLE_CANTON_CICD }}
          aws-lambda-url: ${{ secrets.GATI_AWS_LABDA_URL_INTEGRATIONS }}
          aws-region: ${{ secrets.GATI_AWS_REGION }}
      - name: Post comment
        id: post-comment
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc #v2.8.2
        with:
          repo-token: ${{ steps.setup-github-token.outputs.access-token }}
          refresh-message-position: true
          issue: ${{ github.event.client_payload.github.payload.issue.number }}
          message: |
            ⏳ **Autofix is running...**
            Workflow run: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          install-only: true
          version: ${{ env.GOLANGCI_LINT_VERSION }}
      - name: Install DPM
        uses: ./.github/actions/install-dpm
      - name: Run fixes
        run: make fix-all
      - name: Create commit
        id: commit
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            git config --global user.name "Login will be determined by the Github API based on the creator of the token"
            git config --global user.email ""
            git add -A
            git commit -m "[autofix] apply fix-all to PR"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
      - name: Push signed commits
        if: steps.commit.outputs.has_changes == 'true'
        # use forked push-signed-commits so that commits can be generated when there are DARs
        uses: cfal/push-signed-commits@557a29703a381c8401e55eaf9359fc3751c347c0 # v1
        with:
          github-token: ${{ steps.setup-github-token.outputs.access-token }}
          local_branch_name: ${{ github.event.client_payload.pull_request.head.ref }}
          remote_name: "origin"
          remote_branch_name: ${{ github.event.client_payload.pull_request.head.ref }}
      - name: Update comment
        id: update-comment
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc #v2.8.2
        if: always()
        with:
          repo-token: ${{ steps.setup-github-token.outputs.access-token }}
          refresh-message-position: true
          issue: ${{ github.event.client_payload.github.payload.issue.number }}
          message-success: |
            ✅ **Autofix successful**
            Workflow run: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          message-failure: |
            ❌ **Autofix failed**
            Workflow run: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          message-cancelled: |
            ✖️ **Autofix cancelled**
            Workflow run: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}️
